ansys/pymapdl

- pyansys/ansys.py
for https://github.com/akaszynski/pyansys/issues/111
> fix varname length limit 8 and string varname in *set of load_parameters

- pyansys/mapdl.py
added get_float(); changed start_broadcast_logger (#119 and #120)
> Feature119 120

- pyansys/mapdl_functions.py
Mapdl.k, Mapdl.l, Mapdl.a, Mapdl.al now should return the number of created keypoint line or area
> #131 useful return values

- pyansys/geometry_commands.py
- pyansys/mapdl_functions.py
- tests/test_build_geometry.py
#138 pull out parse_al() from mapdl_functions.py
fix mapdl.k() (original command not available in parse_k())
add test for mapdl.al()
> #138 pull out parse_al() from mapdl_functions.py

- examples/00-read_binary/load_shaft_result.py
- examples/00-read_binary/sector_model.py
- pyansys/__init__.py
- pyansys/_version.py
- pyansys/cyclic_reader.py
- pyansys/cython/_binary_reader.pyx
- pyansys/cython/binary_reader.cpp
- pyansys/rst.py
- tests/test_ansys.py
- tests/test_binary_reader.py
- tests/test_cyclic.py
This PR includes various fixes for v19.4 including:
- Better support for saving in a `VTK` format
- Fixed segfault bug when reading some element results
- Fixed cyclic orientation bug
- Improved documentation
> Negative cyc rotate

- pyansys/cython/_binary_reader.pyx
- pyansys/cython/binary_reader.cpp
- tests/test_binary_reader.py
This PR fixes a particularly nasty memory leak associated with most binary file reads.
> Fix cpp memory leak

- pyansys/_version.py
- pyansys/mapdl.py
- tests/test_ansys.py
This PR fixes interactive plotting and improves the default resolution of outputted images.
> Fixed interactive plotting (0.39.18)

- azure-pipelines.yml
- docs/index.rst
- docs/quality.rst
- pyansys/__init__.py
- pyansys/_cellqual.pxd
- pyansys/archive.py
- pyansys/cell_quality.py
- tests/test_misc.py
This PR adds the cell quality standalone function along with basic documentation.
> Add cell quality standalone function

- .ci/azure-steps.yml
- .gitignore
- azure-pipelines.yml
- pyansys/archive.py
- pyansys/geometry.py
- pyansys/mapdl.py
- pyansys/misc.py
- requirements_build.txt
- requirements_test.txt
- tests/archive/test_archive.py
- tests/elements/test_solid239_240.py
- tests/test_corba.py
- tests/test_examples.py
Azure CI was failing to run unit tests on all platforms.  This PR forces the tests to run, fails the job when `pytest` fails, and fixes the various minor bugs that cropped up due to the tests.
> Fix Azure CI

- pyansys/_version.py
- pyansys/launcher.py
- pyansys/mapdl.py
- pyansys/mapdl_console.py
- pyansys/mapdl_corba.py
- pyansys/mapdl_geometry.py
- pyansys/mesh.py
- pyansys/plotting.py
- tests/test_cyclic.py
Release `0.43.0` broke `open_gui` and this PR fixes the GUI launcher while maintaining the API of the new `launch_mapdl`.
> Fix off_screen testing open_gui

- examples/02-mapdl-examples/transient_thermal.py
- pyansys/_version.py
- pyansys/cython/vtk_support.c
- pyansys/dis_result.py
- pyansys/mapdl.py
- pyansys/mapdl_functions.py
- pyansys/mesh.py
- pyansys/misc.py
- pyansys/parameters.py
- pyansys/rst.py
- tests/test_mapdl.py
- tests/test_post.py
This PR fixes SURF152 parsing and improves distributed result file detection for post-processing.  It also adds a transient thermal post-processing example that demonstrates using `pyvista` to aid in the post-processing of results using a slice example.
Applicable commits:
- fixed surf152 parsing
- add table io and auto-renumber dist results
- cleaned up docs and fixed edge case race condition for point_arrays
- added transient thermal example
> Fix Thermal Result Post-Processing

- pyansys/_version.py
- pyansys/launcher.py
- pyansys/mapdl.py
- pyansys/mesh.py
- pyansys/rst.py
- setup.py
There several bugs cropped up when testing on a clean install with system python 3.8 on Linux (and some additional ones on docker).  This PR addresses those issues, and also a minor bug detected by ``pyvista==0.27.1``.
Commits:
- automatically addressing DMP bug
- make install_requires version explicit
- allow logging failure on collection
- fix invalid consistency check
- version bump to 0.44.12
> Misc Fixes

- pyansys/mapdl_corba.py
- tests/conftest.py
This PR resolves #315 by checking if the CORBA instance has been closed.
> CORBA - Check if instances have been exited

- docs/source/index.rst
These are the intro/background improvements we discussed.  Feel free to adjust.
> general improvements

- ansys/mapdl/core/_version.py
- ansys/mapdl/core/examples/examples.py
- ansys/mapdl/core/examples/wing.dat
- examples/01-apdlmath-examples/eigen_solve.py
- examples/01-apdlmath-examples/mapdl_vs_scipy.py
- setup.py
- tests/test_files/wing.dat
One new test ( mapdl_vs_scpy.py), and some enhancements of existing tests.
> Fred ans/update tests

- ansys/mapdl/core/common_grpc.py
- ansys/mapdl/core/element_commands.py
- ansys/mapdl/core/mapdl.py
- ansys/mapdl/core/mapdl_console.py
- ansys/mapdl/core/mapdl_corba.py
- ansys/mapdl/core/mapdl_grpc.py
- ansys/mapdl/core/math.py
- ansys/mapdl/core/mesh_grpc.py
- ansys/mapdl/core/parameters.py
- ansys/mapdl/core/post.py
- docs/source/getting_started/index.rst
- docs/source/user_guide/index.rst
- tests/test_corba.py
- tests/test_mapdl.py
This PR reduces client/server communication for many methods that do not check or store any response from MAPDL.
Remaining Tasks:
> Reduce Chatter

- ansys/mapdl/core/solution.py
Simple PR to correct ``Solution`` class examples.
> correct solution class examples

- docs/make.bat
- docs/source/contributing.rst
Add additional documentation and build batch for windows.
> Windows Build

- docs/source/getting_started/index.rst
- docs/source/getting_started/running_mapdl.rst
Simple fix to getting started docs.
> Minor Documentation Fixes

- ansys/mapdl/core/mapdl.py
- ansys/mapdl/core/plotting.py
- ansys/mapdl/core/post.py
- docs/source/user_guide/mapdl_examples.rst
- setup.py
- tests/test_console.py
- tests/test_corba.py
- tests/test_mapdl.py
PR with using branch natter1_mapdl instead of fork.
> #423 (pr #422 using new branch)

- ansys/mapdl/core/mapdl.py
- ansys/mapdl/core/plotting.py
- ansys/mapdl/core/post.py
- docs/source/user_guide/mapdl_examples.rst
- tests/test_console.py
- tests/test_corba.py
- tests/test_mapdl.py
* #423 (pr #422 using new branch)
* update tests #426
* update parameter screenshot #426
* screenshot -> savefig
* force maximum version of pyvista
* unclamp pyvista req
* Update ansys/mapdl/core/plotting.py
Co-authored-by: Alex Kaszynski <akascap@gmail.com>
* Update ansys/mapdl/core/mapdl.py
Co-authored-by: Alex Kaszynski <akascap@gmail.com>
* screenshot -> savefig
Co-authored-by: Alex Kaszynski <akascap@gmail.com>
> #423 (pr #422 using new branch) (#426)

- ansys/mapdl/core/mapdl_grpc.py
- tests/test_mapdl.py
Minor test fixes in preparation for v212 merge.
> testing improvements

- .gitignore
- docker/mapdl/Dockerfile
- docker/mapdl/IMAGE_NAME
- docker/mapdl/reduce_mapdl.py
This PR adds some additional notes and build options for building the v212 (2021R2) release.
> add notes for docker build

- docs/source/contributing.rst
- examples/03-tips-n-tricks/00-example-template.py
- examples/03-tips-n-tricks/01-smoothing-element-size-transitions.py
- examples/03-tips-n-tricks/README.txt
This PR also contains the work in https://github.com/pyansys/PyMAPDL/pull/468, and essentially only contains one new example.
> element size transition example

- docs/source/getting_started/faq.rst
- docs/source/getting_started/index.rst
Designed to close https://github.com/pyansys/PyMAPDL/issues/332 and provide a place for further Q&A in the future
> created new FAQ section addressing issue #332

- LICENSE
- ansys/mapdl/core/__init__.py
- ansys/mapdl/core/_commands/aux15_.py
- ansys/mapdl/core/examples/downloads.py
- ansys/mapdl/core/examples/examples.py
- ansys/mapdl/core/mapdl.py
- ansys/mapdl/core/mapdl_grpc.py
- ansys/mapdl/core/mesh_grpc.py
- ansys/mapdl/core/misc.py
- ansys/mapdl/core/plotting.py
- ansys/mapdl/core/theme.py
- examples/00-mapdl-examples/geometry.py
- setup.py
- tests/test_examples.py
This PR adds basic theme support and an example demonstrating themes and low level grid access.
> add theme support and geometry example

- ansys/mapdl/core/_commands/solution/nonlinear_options.py
- ansys/mapdl/core/launcher.py
- docs/source/getting_started/faq.rst
Additionally, add `log_apdl` description, improve handling of options in `launch_mapdl`
> Fix nladaptive args

- ansys/mapdl/core/launcher.py
- ansys/mapdl/core/pool.py
- requirements_test.txt
- tests/test_pool.py
> added note about requiring 2020R2 support

- README.rst
Documentation fix in README.rst#Dependencies
> Minor text fix in Dependencies

- examples/00-mapdl-examples/statically_indeterminate_reaction_force_analysis.py
> Fix formatting in example maths

- examples/03-tips-n-tricks/03-using_inline_functions_and_Query.py
Created example based on the examples used in the UX/Y/Z docstrings.
This example is a *little* bit more detailed and includes plotting, as
well as an example of how to use the Query class to extract data from a
simulation.
> Created example based on UX examples

- ansys/mapdl/core/launcher.py
> fixed example import

- ansys/mapdl/core/_commands/preproc/elements.py
- ansys/mapdl/core/plotting.py
- examples/00-mapdl-examples/contact_elements.py
This PR adds a basic contact element example in response to https://github.com/pyansys/pymapdl/discussions/510
> Add contact elements example

- doc/source/getting_started/running_mapdl.rst
Minor fix to the getting started docs.
> add missing sudo to getting-started

- .github/workflows/smoke-tests.yml
- ansys/mapdl/core/mapdl_corba.py
- ansys/mapdl/core/misc.py
- doc/source/getting_started/index.rst
- setup.py
Missed smoke-test failure on main.  This PR fixes the syntax and builds pymapdl inplace rather than generating and installing the source distribution.
> Fix smoketests

- tests/test_launcher.py
- tests/test_pool.py
Updated versions numbers and removing an odd -1.
> Small fixes.

- .github/workflows/ci.yml
- ansys/mapdl/core/mapdl.py
- ansys/mapdl/core/mesh_grpc.py
- tests/test_mapdl.py
Reverts pyansys/pymapdl#755 to resolve #759.
> Revert "account for edge case with hidden nodes"

- .gitignore
As the title, for the Pycharm users.
> Updated gitignore to exclude PyCharm local settings folder.

- ansys/mapdl/core/mapdl_grpc.py
Resolve #776 by implementing more detailed erros and instructions to solve the import errors.
> Added import error messages regarding outdated API module.

- ansys/mapdl/core/mapdl.py
Close #806 by implementing missing return.
> Added missing return

- doc/source/user_guide/mapdl.rst
Close #802 by:
- Adding `slashsolu` to the docs.
- Shorting the `run_multiline` example.
- Fixing code block in `run_multiline`.
> Fixing broken code block

- doc/source/user_guide/extended_examples/techdemo-1/ex_0-tecbrakesqueal.rst
> Fixing broken links.

- .github/workflows/ci.yml
As the title.
Close #817 by modifying the correspondent ci.yaml file.
> Adding binaries building and uploading to pypi

- ansys/mapdl/core/mapdl.py
- doc/source/api/mapdl.rst
- doc/source/user_guide/mapdl.rst
- tests/test_mapdl.py
Fix #801 by including `input_strings` to `Mapdl` class.
> Feat/adding `input strings` function

- ansys/mapdl/core/commands.py
Fix #828 by properly passing columns to DataFrame constructor.
> Fixing wrong argument passing.

- ansys/mapdl/core/commands.py
- tests/test_commands.py
Adds a unit test for PRNSOL edge case being encountered in #830.
> add prnsol edge case

- ansys/mapdl/core/mapdl.py
- ansys/mapdl/core/mapdl_grpc.py
- tests/test_inline_functions/test_query.py
- tests/test_mapdl.py
> Adding return none to Mapdl

- .coveragerc
- .github/workflows/ci.yml
- codecov.yml
This PR adds codecov support to our CI/CD.
> Add codecov

- .github/workflows/nightly-mapdl-check.yml
- ansys/mapdl/core/mapdl.py
Fix #851 by applying changes #845 to "nightly validate image" `nightly_mapdl_check`.
> Update pytest in nightly mapdl check

- ansys/mapdl/core/launcher.py
> Fix ``launcher_mapdl`` documentation

- ansys/mapdl/core/jupyter.py
Simple patch to correctly pass resource args to our jupyterhub manager.
> fix jupyter resource args

- setup.py
> Adding ``long_description_content_type``

- LICENSE
Bump license date from 2021 to 2022.
> bump license date

- ansys/mapdl/core/mapdl_geometry.py
Close #892 by fixing the doc string.
> fixing anum

- doc/source/conf.py
- doc/source/user_guide/extended_examples/Python_UPF/python_upf_examples.rst
- doc/source/user_guide/extended_examples/ex_01-gmsh_example/ex_01-gmsh_example.rst
- doc/source/user_guide/extended_examples/index.rst
- doc/source/user_guide/extended_examples/techdemo-1/ex_0-tecbrakesqueal.rst
- doc/source/user_guide/index.rst
This PR adds breadcrumbs to our docs to make it clear where you are in the navigation tree.
Also improves extended example section styling and examples.
> Add breadcrumbs

- examples/07-technology-showcase-examples/20-example-technology-showcase-dynamic-simulation-PCB.py
In this PR, I am adding minor adjustments to the example of the dynamic simulation of a PCB.
> Minor adjustments to PCB example

- pyproject.toml
> Bumping to 0.62.dev

- tests/test_math.py
To resolve a comment done in #944. 
Link: https://github.com/pyansys/pymapdl/pull/944#discussion_r822709581
> Improving unit test for `math.status`

- doc/source/user_guide/extended_examples/Python_UPF/python_upf_examples.rst
Close #1016 by fixing indentation.
> Fixing indentation in UPF python example

- doc/source/getting_started/wsl.rst
> Small fixes in the WSL Guide

- doc/source/user_guide/index.rst
Removing obsolete section regarding the command output.
> Removing obsolete section

- src/ansys/mapdl/core/launcher.py
- tests/test_launcher.py
Improving the documentation and usage.
Close #1014
> Improving `save_ansys_path` function

- .ci/start_mapdl.sh
- .github/workflows/ci.yml
- .github/workflows/nightly-doc-build.yml
- .github/workflows/nightly-mapdl-check.yml
- requirements/requirements_tests.txt
As the title.
Now don't use env vars, only secrets and actions.
> Improving Github docker registry logging

- .github/release.yml
They seems to not work, and I believe it might be because of this.
> Fixing release notes

- .github/labeler.yml
- .github/release.yml
- .github/workflows/label.yml
As the title.
I believe a mix of wrong labels (because of capitalization), bad syntax (negation in github is `!`), and useless triggers broken this workflow.
Feedback is appreciated. 
**Reference**: https://github.com/pyansys/pymapdl/actions/runs/2206989769
> Fix pull request labeler

- README.rst
> Add PyAnsys badge in README.rst

- .github/workflows/ci.yml
- README.rst
- doc/source/getting_started/index.rst
By popular request, adds wheelhouse CI.
> add wheelhouse CI

- .github/workflows/label.yml
> Fix labels name in autolabeler

- .github/dependabot.yml
Just a quick fix after seeing the behavior in #1098.
> Fix dependabot labeler

- src/ansys/mapdl/core/mapdl_grpc.py
- src/ansys/mapdl/core/misc.py
- tests/test_misc.py
> Fixing missing warn import

- src/ansys/mapdl/core/mapdl_grpc.py
- tests/test_mapdl.py
Close #1074 by fixing function with wrong identation.
> Fixing `TBFT` not working

- .gitignore
- src/ansys/mapdl/core/launcher.py
- src/ansys/mapdl/core/pool.py
Noticed some minor errors when reading through the [LocalMapdlPool](https://mapdldocs.pyansys.com/api/_autosummary/ansys.mapdl.core.pool.LocalMapdlPool.html) documentation.
> Minor pool documentation cleanup

- src/ansys/mapdl/core/misc.py
> Fix empty arg in ``_get_args_xsel``

- src/ansys/mapdl/core/mapdl.py
> Fix nplot example

- doc/source/conf.py
Fix language warning which might be reason why #1167 does not pass.
> Fix language warning

- src/ansys/mapdl/core/_commands/solution/analysis_options.py
Fix #1180 
I fixed some more commands, but I could stay fixing forever.
> Fix `ANTYPE` docstring

- examples/00-mapdl-examples/cyclic_analysis.py
- pyproject.toml
Quick fix for the cyclic analysis example.
> Fix cyclic example

- .github/ISSUE_TEMPLATE/bug.yml
To add text box for the report.
> Updated bug template

- .github/workflows/label.yml
> Fixing labeler not working

- src/ansys/mapdl/core/_commands/post26_/special.py
- src/ansys/mapdl/core/mapdl.py
- src/ansys/mapdl/core/mapdl_grpc.py
- src/ansys/mapdl/core/misc.py
- src/ansys/mapdl/core/parameters.py
- tests/conftest.py
- tests/test_mapdl.py
- tests/test_misc.py
- tests/test_parameters.py
As the title.
I am basically modifying VGET to output the variable.
> Returning variables as array in NSOL and ESOL

- src/ansys/mapdl/core/__init__.py
- src/ansys/mapdl/core/_version.py
- src/ansys/mapdl/core/launcher.py
- tests/conftest.py
- tests/test_pool.py
Currently Ansys Students versions are not supported because they don't follow traditional Ansys installation path directives.
I have also updated the supported versions in the tests.
Close #1332
> Adding ansys student support

- src/ansys/mapdl/core/post.py
- tests/test_post.py
> Correct misnamed `nnum` to `enum`

- doc/source/user_guide/mapdl.rst
- src/ansys/mapdl/core/_commands/session/files.py
- src/ansys/mapdl/core/mapdl.py
- src/ansys/mapdl/core/mapdl_grpc.py
- tests/test_convert.py
- tests/test_mapdl.py
Resolve #1357 by adding `lgwrite` functionality.
Thanks for pointing this out @mikerife.
Pinging @mcMunich for visibility. We'll have this included in `ansys-mapdl-core==0.64.0`.
> add lgwrite cleanup functionality

- .github/workflows/ci.yml
- doc/source/mapdl_commands/map.rst
- src/ansys/mapdl/core/_commands/map_cmd.py
- src/ansys/mapdl/core/_commands/session/processor_entry.py
The map function was duplicated.
> Removing redundant map function

- .github/ISSUE_TEMPLATE/bug.yml
> Including checkbox for updated environment in bug template

- .github/workflows/ci.yml
- .github/workflows/nightly-mapdl-check.yml
- requirements/requirements_tests.txt
- tests/test_dpf.py
Implementation of DPF in the CICD for the unit tests and doc build.
> DPF for testing in CICD

- doc/source/getting_started/index.rst
- doc/source/learning/index.rst
- doc/source/troubleshoot/troubleshoot.rst
- src/ansys/mapdl/core/launcher.py
- tests/test_launcher.py
Close #1485 by enforcing ``smp`` in student versions.
> Forcing SMP in student versions.

- src/ansys/mapdl/core/_version.py
Ahead of release time, we should be able to support this version too.
> Adding v23.1 support

- .github/ISSUE_TEMPLATE/bug.yml
> Bug template improvements

- doc/source/contribution_and_api/index.rst
- src/ansys/mapdl/core/mapdl.py
- src/ansys/mapdl/core/mapdl_console.py
- src/ansys/mapdl/core/mapdl_corba.py
- src/ansys/mapdl/core/mapdl_grpc.py
- tests/test_console.py
- tests/test_corba.py
- tests/test_grpc.py
- tests/test_mapdl.py
I think it is a nicer way to check if the instance is 'grpc' or not.
> Mode exposed in Mapdl class

- examples/00-mapdl-examples/lathe_cutter.py
> Small style fix to lathe example

- src/ansys/mapdl/core/commands.py
- tests/test_commands.py
As the title.
Related to #1548
> Implement extra methods in ``NLIST`` command

- doc/source/user_guide/krylov.rst
- requirements/requirements_docs.txt
- requirements/requirements_tests.txt
I finished my editorial review and attempted to correct issues pointed out by Mechanical APDL writers. Note that this may be the only page that uses Mechanical APDL rather than MAPDL. We might have to do some search and replaces in a separate PR, perhaps after the change to sentence case titles is completed.
> Quick edit of Krylov topic

- src/ansys/mapdl/core/licensing.py
- src/ansys/mapdl/core/logging.py
- tests/test_logging.py
Small improvements:
* Removing over logging in licensing
* Accepting lower case log levels.
> Small improvements to logging

- src/ansys/mapdl/core/_commands/database/setup.py
- src/ansys/mapdl/core/_commands/post1_/setup.py
- src/ansys/mapdl/core/post.py
- tests/test_post.py
Added also unit tests.
Fixed some docstring format as well.
> Improving docstrings in post.

- .github/workflows/ci.yml
> Adding timeout to windows and local ubuntu jobs.

- .github/workflows/ci.yml
Disabling Windows tests until we can figure out how to rerun the test (fixtures included).
Close #1694
> Disabling Windows tests.

- .github/workflows/dev-docs-publish.yml
Fix bug introduced in https://github.com/pyansys/pymapdl/pull/1698
> Adding downloader from other workflows

- .github/workflows/dev-docs-publish.yml
Let's try again the artifacts downloader.
> Fix dev-doc uploader

- doc/source/api/commands.rst
- doc/source/getting_started/faq.rst
- doc/source/getting_started/using_julia.rst
- doc/source/user_guide/post.rst
- src/ansys/mapdl/core/_commands/database/selecting.py
- src/ansys/mapdl/core/commands.py
- src/ansys/mapdl/core/mapdl.py
- src/ansys/mapdl/core/mapdl_geometry.py
- src/ansys/mapdl/core/misc.py
- tests/test_commands.py
- tests/test_mapdl.py
- tests/test_plotting.py
> `XSEL` commands return ids

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
Fixing dev container setup by adding licensing env var
> Fix devcontainer setup

- .github/workflows/ci.yml
> Removing ubuntu local from release requirements

- pyproject.toml
Upgrading dev version because of 0.64 release.
> Upgrading dev version.

- .github/workflows/ci.yml
> Adding v23.1 to the CI/CD

- .github/workflows/label.yml
> Attemping to resync the labels to avoid later comment

- .pre-commit-config.yaml
Updating ``pre-commit`` with ``isort`` fix.
Thanks to @RobPasMue
> Updating pre-commit

- LICENSE
Ultra trivial. This should be automated by a bot. @jorgepiloto, this is just begging for an action...
> Bump year in copyright to 2023

- src/ansys/mapdl/core/launcher.py
- tests/test_launcher.py
> Allowing floats as argument. Updating docstring

- .github/workflows/approver.yml
> Allowing pyansys bot to approve my prs 

- doc/source/user_guide/troubleshoot.rst
- src/ansys/mapdl/core/launcher.py
Close #1879 
Pinging @rajesh1359
> Increasing timeout

- docker/Dockerfile
- docker/make_container.rst
> Small fixes to the docker documentation

- src/ansys/mapdl/core/_version.py
For developing purpuses mainly.
> Adding support to v23.2

- src/ansys/mapdl/core/plotting.py
> Exposing some Pyvista kwargs in ``general_plotter`` functions

- .github/workflows/label.yml
- .github/workflows/nightly-doc-build.yml
- .github/workflows/nightly-mapdl-check.yml
> Fix nightlies

- .github/workflows/ci.yml
> Simpliying smoke tests matrix

- .github/workflows/ci.yml
- doc/source/_templates/sidebar-nav-bs.html
- doc/source/conf.py
- requirements/requirements_doc.txt
- requirements/requirements_tests.txt
- src/ansys/mapdl/core/_commands/solution/load_step_operations.py
> Applying pyansys/actions v0.4 patch on 0.63

- .github/workflows/ci.yml
- doc/source/_templates/sidebar-nav-bs.html
- doc/source/conf.py
- requirements/requirements_doc.txt
- requirements/requirements_tests.txt
> Applying pyansys/actions v0.4 patch on 0.62

- .ci/start_mapdl.sh
- .github/workflows/ci.yml
- doc/source/_templates/sidebar-nav-bs.html
- doc/source/conf.py
- requirements/requirements_doc.txt
- requirements/requirements_tests.txt
> Applying pyansys/actions v0.4 patch on 0.61

- pyproject.toml
Because of logo changes, pushing this before dependabot.
> Updating sphinx theme

- .github/workflows/ci.yml
> Allowing extended testing on release

- .github/workflows/ci.yml
Let's test on v23.1 and v23.2 for the moment.
> Adding v23.2 and switching to private containers

- doc/source/getting_started/learning.rst
> Fixing cheatsheet link

- doc/source/user_guide/mapdl.rst
Improving documentation about env vars
> Improving env var section

- doc/source/user_guide/post.rst
- examples/00-mapdl-examples/composite_dcb.py
> Small fixes and typos

- src/ansys/mapdl/core/mapdl.py
- src/ansys/mapdl/core/mesh_grpc.py
- tests/test_mapdl.py
- tests/test_mesh_grpc.py
> Implementing ``rlblock``'s methods to parse ``R`` constants

- doc/source/api/mapdl.rst
- doc/source/user_guide/mapdl.rst
- src/ansys/mapdl/core/mapdl.py
> Expanding ``non_interactive`` documentation

- src/ansys/mapdl/core/docs.py
- src/ansys/mapdl/core/mapdl.py
- tests/conftest.py
- tests/test_launcher.py
This is a routinary PR. After quite a few time without checking on Windows side, I decided to run all the tests locally.
* Fix and improve "open_gui" tests Close #1889 
* Fix docs test to return "/" instead "\\".
> Windows tests

- .github/workflows/ci.yml
- .github/workflows/nightly-doc-build.yml
- pyproject.toml
> maint: change PyAnsys actions ref

- src/ansys/mapdl/core/docs.py
- src/ansys/mapdl/core/misc.py
- tests/conftest.py
- tests/test_docs.py
This should fix the tests when releasing
> Using a function to get branch name

- .github/ISSUE_TEMPLATE/bug.yml
Improving bug template.
* Fixed links.
* Improved layout
* Added more emojis
> Improving bug template

- pyproject.toml
> Bump to 0.66

- tests/test_mapdl.py
We are making the version upper bound time dependent.
> Fixing upper version limit

- .github/workflows/ci.yml
> Rendering the last 5 versions in documentation

- pyproject.toml
Adding trame dependency for doc building.
> Adding trame

- pyproject.toml
Because of warnings, we have updated pymapdl-reader.
> Updating pymapdl-reader

- .github/workflows/linkchecker.yml
- doc/source/conf.py
- pyproject.toml
> Fix redirection and link checker

- docker/docker-compose.dpf.yml
- docker/docker-compose.license_server.yml
- docker/docker-compose.yml
> Updating docker targets

- src/ansys/mapdl/core/mapdl.py
- tests/test_plotting.py
> Supporting CMPLOT

- pyproject.toml
> Update sphinx to 7.1.1

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
> Small improvements to issues templates

- .github/workflows/ci.yml
> Adding v24.1 to cicd

- doc/source/getting_started/versioning.rst
> Fixing vale warnings

- doc/source/conf.py
- pyproject.toml
- src/ansys/mapdl/core/theme.py
- tests/test_dpf.py
- tests/test_pool.py
* Updating pyvista to 0.41
* Updating reader
* Removing rcParams
* Using pyvista 0.41.1
* Avoiding importing dpf.
* adding missing import
* Update tests/test_dpf.py
* maint: updating `ansys-dpf-core` version
* test: fixing `test_heal`
* [pre-commit.ci] auto fixes from pre-commit.com hooks
for more information, see https://pre-commit.ci
* test: revert last commit
---------
Co-authored-by: Camille <78221213+clatapie@users.noreply.github.com>
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
> Update release branch for 0.65.2

- .github/workflows/approver.yml
> Fixing link in approver comment

- src/ansys/mapdl/core/_commands/preproc/booleans.py
- src/ansys/mapdl/core/mapdl_grpc.py
As the title.
Close #2265
Close #2266
> Fix ASBL command

- pyproject.toml
- src/ansys/mapdl/core/plotting.py
> Updating ansys-sphinx-theme to 0.10.4

- .devcontainer/README.rst
- .github/workflows/label.yml
- README.rst
- doc/source/api/building_example.rst
- doc/source/getting_started/contribution.rst
- doc/source/getting_started/index.rst
- doc/source/getting_started/versioning.rst
- docker/make_container.rst
- examples/00-mapdl-examples/pressure_vessel.py
- src/ansys/mapdl/core/docs.py
- src/ansys/mapdl/core/examples/downloads.py
- src/ansys/mapdl/core/jupyter.py
- src/ansys/mapdl/core/mapdl.py
- src/ansys/mapdl/core/mapdl_grpc.py
- src/ansys/mapdl/core/plotting.py
- tests/test_docs.py
- tests/test_grpc.py
> More reorg rebranding

- examples/00-mapdl-examples/2d_plate_with_a_hole.py
Just testing the github web for changing code and also the link from the docs.
> Quick fix in an example

- .ci/start_mapdl.sh
- .ci/start_mapdl_ubuntu.sh
- .github/workflows/ci.yml
- tests/test_solution.py
> Allowing extended testing on dispatch (optional) and schedule

- .devcontainer/docker-compose.yml
- .devcontainer/script.sh
* Using a different port to exposing the inteface externally.
* Automatically installing packages for testing and doc building.
> Small improvements in the devcontainer configuration

- .github/workflows/ci.yml
> Adding codecov token

- doc/source/getting_started/learning.rst
- doc/source/links.rst
> Added articles to recommended

- tests/conftest.py
- tests/test_launcher.py
- tests/test_launcher_remote.py
- tests/test_licensing.py
- tests/test_mapdl.py
- tests/test_pool.py
> Using quicker configuration to launch mapdl in unit tests

- pyproject.toml
> Bumping to 0.67.dev

- .github/workflows/ci.yml
- pyproject.toml
- update the stable indexing workflow
- update the theme version  to fix the issue with search frontend
> fix: update the search indexing workflow and dependency

- pyproject.toml
> Updating pyvista doc dependency

- doc/Makefile
- doc/source/conf.py
- doc/source/examples/devportal.rst
- doc/source/examples/index.rst
- doc/source/links.rst
- pyproject.toml
To take advantages of the articles published there.
Close #2448
> Adding dev portal articles section

- .ci/run_vms.py
- .github/workflows/ci.yml
- pyproject.toml
> Adding global unit test duration limit

- doc/source/conf.py
- doc/source/index.rst
- doc/source/links.rst
> Referencing the PDF in the docs

- .github/workflows/ci.yml
- .github/workflows/docker_clean_untagged.yml
> Updating ansys actions to v5

- .ci/start_mapdl.sh
- .ci/start_mapdl_student.sh
- .ci/start_mapdl_ubuntu.sh
- .github/workflows/ci.yml
As the title.
Remove secrets from unit testing.
> Removing secrets from CICD: Part 2 Testing

- .devcontainer/Dockerfile
- .devcontainer/README.rst
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/start.sh
As the title. 
I still need to add the docs.... one day..........
> Adding python virtual environment to codespaces

- LICENSE
> Updating license and copyright

- .github/workflows/ci.yml
- pyproject.toml
> Updating grpcio and adding missing env var.

- .github/labels.yml
- .github/workflows/ci.yml
> Updating labels

- .devcontainer/codespaces-docs/requirements.txt
> Fix requirement file in codespaces doc

- .github/dependabot.yml
> Avoiding different groups in devcontainer dependabot PRs

- src/ansys/mapdl/core/launcher.py
> Improving logging when starting fails

- .github/workflows/approver.yml
> Adding gif to approval bot mesage

- README.md
> Adding codespace info in readme

- pyproject.toml
Bump ansys-sphinx-theme version to `0.13.1`
> maint: bump-ansys-sphinx-theme-version

- pyproject.toml
> Limiting numpy to v2.0.0

- src/ansys/mapdl/core/errors.py
> Replacing with super() in custom error classes

- tests/test_convert.py
As the title.
Since I had to write this code for testing #2674 I might as well add it to the tests.
> Adding test to DSCALE

- .devcontainer/codespaces-docs/devcontainer.json
- .devcontainer/codespaces-docs/start.sh
- .devcontainer/devcontainer-local/devcontainer.json
- .devcontainer/devcontainer-local/start.sh
- .devcontainer/devcontainer.json
- .devcontainer/start.sh
> Fix codespaces no loading extensions

- pyproject.toml
> fix: pyvista version

- pyproject.toml
> Adding memory profiling pytest extension

- src/ansys/mapdl/core/launcher.py
> fix: launch_mapdl with specific ip value

- .devcontainer/codespaces-docs/welcome.rst
> Small improvements to documentation codespace

- src/ansys/mapdl/core/convert.py
- tests/test_convert.py
> Small improvements to converter

- src/ansys/mapdl/core/mapdl_geometry.py
- src/ansys/mapdl/core/plotting.py
- tests/test_plotting.py
> Fixing nodes label order

- src/ansys/mapdl/core/mapdl_extended.py
- src/ansys/mapdl/core/mapdl_geometry.py
- src/ansys/mapdl/core/plotting.py
It should fix the doc building issues seen in the nightly.
Close #2752
> Delete array after retrieving

- .github/workflows/ci.yml
> Installing xindy to fix PDF building process

- src/ansys/mapdl/core/mapdl_grpc.py
As the title.
Related to https://github.com/ansys/pymapdl/issues/2681
> Avoiding issuing exit on any version until further notice

- examples/00-mapdl-examples/contact_elements.py
> Fix contact example

- .devcontainer/codespaces-dev/requirements.txt
- .devcontainer/codespaces-docs/requirements.txt
- .devcontainer/devcontainer-local/requirements.txt
- pyproject.toml
- tests/test_database.py
> Fix nightly

- .github/workflows/ci.yml
> Fixing release not finding minimum requirements file

- .github/workflows/ci.yml
> Fix release (again)

- .github/workflows/ci.yml
> Fix release again^2

- pyproject.toml
> Update to 0.69.dev

- .devcontainer/codespaces-dev/requirements.txt
- .devcontainer/codespaces-docs/requirements.txt
- .devcontainer/devcontainer-local/requirements.txt
> Update Pandas in codespaces

- .devcontainer/codespaces-dev/requirements.txt
- .devcontainer/codespaces-docs/requirements.txt
- .devcontainer/devcontainer-local/requirements.txt
The libraries broke doc builds.
> Downgrading packages

- .github/workflows/ci.yml
> Setting julia cicd

- src/ansys/mapdl/core/mapdl_grpc.py
> Fix edge case were MAPDL to start and we do not initialize self._version

- .github/workflows/cache_cleaner.yml
> Fixing infinite loop cache cleaner

- pyproject.toml
- src/ansys/mapdl/core/__init__.py
> Update minimal python version

- src/ansys/mapdl/core/misc.py
As the title. They are useful to print for PyMAPDL.
> Adding some env var print to report

- doc/source/conf.py
> Avoiding future shinx warning

- doc/source/getting_started/launcher.rst
- doc/source/getting_started/wsl.rst
- doc/source/links.rst
- doc/source/user_guide/cli.rst
- doc/source/user_guide/mapdl.rst
- doc/source/user_guide/troubleshoot.rst
- doc/source/user_guide/upf.rst
> Setting docs version to v241

- src/ansys/mapdl/core/cli/hpc.py
- src/ansys/mapdl/core/hpc/pyhps.py
> Adding APDL jobs support

- .github/workflows/ci.yml
Remove `texlive-xetex` duplicate form docs-build job
> CI: Remove OS package duplicate

- .github/labels.yml
As the title.
To facilitate doc reviews.
> Adding tag for doc review

- doc/source/user_guide/mapdl.rst
> Update a minor typo in mapdl.rst

- .github/labels.yml
- .github/release.yml
- .github/workflows/label.yml
- doc/changelog.d/3188.fixed.md
Use the same (case-sensitive) labels everywhere
Close #3184
> fix: using same labels everywhere

- .github/workflows/ci.yml
- doc/changelog.d/3211.changed.md
Using last 2 julia versions
Update CICD to use the last 2 julia versions
Skipping julia testing if not in certains specific events (PR, schedule, or dispatch).
> ci: Update julia testing

- .github/workflows/ci.yml
- doc/changelog.d/3282.fixed.md
> fix: increasing timeout for local-min

- .pre-commit-config.yaml
- doc/changelog.d/3339.changed.md
Update ansys pre-commit hook
NA
> build: update pre-commit-hook

- doc/changelog.d/3340.miscellaneous.md
- src/ansys/mapdl/core/mapdl_grpc.py
- tests/test_grpc.py
Adding a method to retrieve the gRPC channel status through channel subscription.
NA
> feat: adding channel subscription method and tests

- doc/changelog.d/3449.documentation.md
- doc/source/conf.py
- doc/source/helpers.py
- doc/source/index.rst
Hide certain elements.
This is a workaround, ideally we should not generate the elements in the first place. But that would require to pass the argument to the builder... consider it in the 'edit-this-page.html' template... etc etc...
I find this can be useful in the future anyways.
NA
> docs: adding directive to hide elements

- doc/changelog.d/3439.fixed.md
- src/ansys/mapdl/core/mapdl_extended.py
- src/ansys/mapdl/core/plotting/theme.py
- tests/test_theme.py
While working on a presentation I saw this small bugs that should be fixed.
NA
> fix: small plotting fix

- .github/workflows/ci.yml
- doc/changelog.d/3468.fixed.md
- doc/source/conf.py
**Please provide a brief description of the changes made in this pull request.**
> fix: add ``build cheatsheet`` as env variable within doc-build

- doc/changelog.d/3463.fixed.md
- src/ansys/mapdl/core/errors.py
- src/ansys/mapdl/core/mapdl_grpc.py
> fix: exiting earlier to avoid exceptions from gRPC calls

- doc/changelog.d/3488.documentation.md
- doc/source/conf.py
Following https://github.com/ansys/pyansys-geometry/pull/1489 's path.
NA
> ci: avoiding linkcheck on changelog page

- doc/changelog.d/3526.documentation.md
- doc/source/index.rst
Removing the extra links and going for links on the grid cards, instead of just using the cards as links containers.
Related to: https://github.com/ansys/ansys-sphinx-theme/issues/552
NA
> docs: removing extra links from landing page.

- README.md
- doc/changelog.d/3525.fixed.md
Fix logo as in https://github.com/ansys/pyansys-geometry/pull/1420
NA
> fix: logo link

- doc/changelog.d/3571.miscellaneous.md
- src/ansys/mapdl/core/_version.py
> feat: supporting v25.1 and v25.2

- doc/changelog.d/3575.miscellaneous.md
- src/ansys/mapdl/core/launcher.py
As the title. To simplify stuff.
NA
> feat: running MPI fix only if on windows

- doc/changelog.d/3582.fixed.md
- doc/source/user_guide/components.rst
- src/ansys/mapdl/core/component.py
> fix: components typo

- .github/workflows/codeql.yml
- doc/changelog.d/3585.maintenance.md
Adding codeql for error checking
NA
> ci: adding codeql.yml

- .ci/build_matrix.sh
- .github/workflows/ci.yml
- doc/changelog.d/3623.maintenance.md
We need to fix some required checks on CICD.
NA
> ci: adding student back

- .github/workflows/ci.yml
- doc/changelog.d/3624.maintenance.md
As the title.
Related issues https://github.com/ansys/actions/pull/658
> ci: temporary skipping attrs license check

- doc/changelog.d/3638.maintenance.md
- src/ansys/mapdl/core/launcher.py
As the title. Fix the `check_vulnerability` action in the CICD
NA
> ci: fix safety issue

- .pre-commit-config.yaml
- LICENSE
- doc/changelog.d/3667.maintenance.md
As the title. Due to `v0.5.0` has been yanked. 
NA
> ci: downgrade add-license-headers ansys precommit hook.

- doc/changelog.d/3664.added.md
- tests/test_component.py
> refactor: using test class in test_components.py

- doc/changelog.d/3684.documentation.md
- src/ansys/mapdl/core/post.py
Fix post documentation
Close #3680
> docs: fix post documentation

- .ci/build_matrix.sh
- doc/changelog.d/3690.maintenance.md
> ci: skipping non-student versions when running on remote

- .devcontainer/codespaces-docs/requirements.txt
- .devcontainer/devcontainer-local/requirements.txt
- doc/changelog.d/3733.dependencies.md
- pyproject.toml
As the title, update sphinx-autodoc-typehints
Related to #2953
> build: update sphinx-autodoc-typehints to 3.0.1

- doc/changelog.d/3729.fixed.md
- src/ansys/mapdl/core/_commands/solution/dynamic_options.py
Fix `HARFRQ` command.
Close #3722
> fix: harfrq command

- doc/changelog.d/3786.documentation.md
- doc/changelog.d/changelog_template.jinja
- minimum_requirements.txt
> docs: update towncrier template

- .github/actions/pytest-summary/action.yml
- doc/changelog.d/3851.fixed.md
Avoid running pytest-summary step if no artifacts have been downloaded.
NA
> fix: add check for artifacts directory before processing files

- doc/changelog.d/3858.fixed.md
- docker/Dockerfile
> fix: remove duplicated lines

- docker/make_container.rst
cp and docker build both requires a path at the end
TAG must be lowercase
> docs: Incorrect container build documentation

- .github/workflows/migrator.yml
> fix: migrator workflow part 1

- doc/changelog.d/3980.fixed.md
- doc/source/conf.py
As the title. Fix plotly plots on the docs.
Close #3958
> fix: plotly on docs

- doc/changelog.d/4129.miscellaneous.md
- pyproject.toml
- src/ansys/mapdl/core/mapdl_core.py
- src/ansys/mapdl/core/reader/result.py
- tests/test_result.py
As the title. Adding type hints and checking numpydoc.
NA
> refactor: adding type hints to result.py

- .github/workflows/ci.yml
- doc/changelog.d/4248.fixed.md
Removing unnecessary artifacts.
> fix: removing artifacts
