pyansys/common.py, pyansys/cython/_binary_reader.pyx
Raising `NotImplementedError` for sparse results.  This is a temporary fix until a more permanent solution can be implemented.
=> Sparse reader

pyansys/_version.py, pyansys/cython/_binary_reader.pyx, pyansys/cython/binary_reader.cpp, pyansys/cython/binary_reader.h, pyansys/rst.py
32-bit pointers were causing segfaults when reading beyond `2^32` bits.  Using int64 fixes this.
=> Added int64 pointers

.gitignore, pyansys/rst.py, requirements_docs.txt, tests/test_rst.py
This is a minor PR that fixes the scalar bar for plotting with ``plot_principal_nodal_stress`` and a few other methods.
Additionally, it adds the method ``plot_nodal_displacement`` as this is a bit more familiar than ``plot_nodal_solution``.  Methods are wrapped to avoid code duplication.
=> fixed stitle for various plotting methods

pyansys/_version.py, setup.py
This PR requires `vtk<=9.0.0` until the Python 3.8 and VTK v9 fixes go through.  Also includes cython check should a non-support platform build be desired.
=> Setup update and version bump to 0.40.1

azure-pipelines.yml, docs/Makefile, docs/apdl_conversion.rst, examples/01-mapdl-examples/README.txt, examples/01-mapdl-examples/pyvista_mesh.py, pyansys/archive.py, pyansys/cyclic_reader.py, pyansys/cython/vtk_support.c, pyansys/mapdl.py, pyansys/rst.py
Several fixes/changes:
- Fix triangle parsing.  Much cleaner meshes from surface elements.
- Improved archive support for surface meshes.  Added the option to save just surface/solid elements to archive.
- Added documentation support for MAPDL demos.  More to come!
- Added MAPDL PyVista interoperability demo.
- Fixed `read_float_parameter` and improved documentation for arrays
=> Fix triangle parsing and add surface support

.gitignore, pyansys/cython/_reader.pyx, pyansys/cython/vtk_support.c, pyansys/cython/vtk_support.h, setup.py, tests/test_corba.py
Darwin on 10.14 and above doesn't like `__inline` and prefers `static inline`.  Performance is the same cross-platform.
Resolves #244.
=> Using static inline

docs/ansys_control.rst, docs/ansys_examples.rst, docs/ansys_functions.rst, docs/index.rst, examples/01-mapdl-examples/mapdl_3d_beam.py, examples/README.txt, pyansys/_version.py, pyansys/cython/_reader.pyx, pyansys/cython/reader.c, pyansys/cython/reader.h, pyansys/geometry.py, pyansys/mapdl.py, tests/test_corba.py
This PR adds the `load_array` method to `mapdl`.  It's basically an interface to `*VREAD`, but to the user it seamlessly transfers `numpy` arrays or python lists to MAPDL.  In the future this will be replaced by a gRPC interface, but for now this allows `pyansys` to backport `load_array` for earlier versions of MAPDL.
Usage
```python
>>> arr = np.array([10, 20, 30])
>>> mapdl.load_array(arr, 'MYARR')
>>> parm, mapdl_arrays = mapdl.load_parameters()
>>> mapdl_arrays['MYARR']
array([10., 20., 30.])
```
```python
>>> arr = np.random.random((5, 3))
>>> mapdl.load_array(arr, 'MYARR')
>>> parm, mapdl_arrays = mapdl.load_parameters()
>>> mapdl_arrays['MYARR']
array([[0.39806635, 0.15060953, 0.3990557 ],
[0.26837768, 0.02033222, 0.15655861],
[0.46110226, 0.06381489, 0.20068533],
[0.20122863, …
```
=> Add array transfer

pyansys/_version.py, pyansys/archive.py, pyansys/cython/reader.c, pyansys/mapdl.py
This PR fixes a bug with a simple but important edge case where the archive file scientific notation contains an `"e"` instead of the standard `"E"`.
Also allows the passing of additional keyword arguments from the `run` command to allow for subclasses of `_MapdlCore` to specify additional kwargs when using `run`.
=> Fix Archive Scientific Notation

pyansys/_version.py, pyansys/cyclic_reader.py
Quick fix to account for a single repeated mode pair when processing cyclic results.
=> Account for single mode pair edge case

pyansys/_version.py, pyansys/mapdl_geometry.py
This PR fixes an edge case on Windows where the underlying mesh forces the creation of a quadratic surface plot using MESH200 despite setting KEYOPT1=4.  Fix is to simply force a linear representation of the surface plot.
Commits:
- patch edge case with quadratic surface plot on windows
- remove commented ugrid for surface extraction
=> Fix quadratic surface plotting

docs/conf.py, examples/02-mapdl-examples/path_operations.py, pyansys/_version.py, pyansys/mapdl.py, pyansys/mapdl_corba.py, pyansys/parameters.py, tests/test_dist_rst.py, tests/test_mapdl.py
As it turns out, `path` is a MAPDL command (interpolate along path), and the Mapdl class has been using it as the path variable.  This PR refactors `path` to `directory` and adds a path operation example in response to issue #272.
<details>
<summary>Commit Summary</summary>
- path --> directory
- add path operation example
- actually add path operation example
- version bump to 0.44.5
</details>
=> Add Path Operations

pyansys/_version.py, pyansys/cyclic_reader.py, pyansys/rst.py
This PR fixes a small bug where pyansys improperly reports complex content of a non-complex mode when the result file contains only one result.
=> Fix single cyclic result with no complex content bug

azure-pipelines.yml, pyansys/_version.py, pyansys/launcher.py, pyansys/mapdl.py, pyansys/mapdl_functions.py, setup.py
Issue #291 noted that two commands were improperly formatting the keyword arguments when parsing commands.  Turns out that there are many commands that include `unused` keyword arguments unnecessarily in the python commands, or have improperly assembled the commands based on the latest ANSYS documentation.
This PR corrects 50+ commands and updates some of the documentation based on changes in MAPDL between 16.0 (when this documentation was built) and the latest current documentation from 2020R2.
It also drops support for Python 3.5 as it has reached its end of life as of [September 2020](https://www.python.org/downloads/release/python-3510/#:~:text=Python%203.5%20will%20reach%20its,release%20of%20the%203.5%20series.).
=> Remove Unused Keyword Arguments

pyansys/_version.py, pyansys/cython/_reader.pyx
This PR corrects a bug where read in component names that have not had their component names striped.  This bug results in extra characters and deviates from the established behavior in `pyansys<=0.44.0` prior to the mesh/reader refactor.
=> Strip Component Names

pyansys/_version.py, pyansys/cython/_binary_reader.pyx
This PR resolves #305 where there was a bug that opened/closed the result file when reading each element's connectivity.  Framework was already in place to open once with `read_record_stream`.  This PR also removes an extra array copying step when reading in `int` values from the result file (written by default).
Bumps version to ``pyansys==0.44.15``
=> use read_record_stream when storing elements

pyansys/archive.py, pyansys/cython/_reader.pyx, pyansys/cython/reader.c, pyansys/mesh.py
This PR patches the ``pyansys.Archive`` class to allow for the reading of *.dat files.  Given that the reader/writer for MAPDL is different than the one used for ANSYS mechanical workbench, several allowances are made in the reader to allow for the variation in syntax and capitalization.
There is an edge case when reading archive files with missing mid-side nodes where NANs are stored within points causing unintended side-effects for any downstream applications.
Update version to ``pyansys==0.44.15``
=> Permit *.dat as Archive Objects

pyansys/_version.py, pyansys/cython/_reader.pyx, pyansys/cython/reader.c
Patches an edge case where unwritten mid-side nodes are not written in a MAPDL EBLOCK.
Bumps version to ``0.44.17``
=> fix edge case with missing mid-side nodes

pyansys/_version.py, pyansys/cython/vtk_support.c
Quick patch for quadratic shell element parsing due to forgetting to set the `is_quad` parameter when building shell elements within `vtk_support`.
=> fix missing is_quad specification

pyansys/_rst_keys.py, pyansys/_version.py, pyansys/cython/_binary_reader.pyx, pyansys/cython/_reader.pyx, pyansys/parameters.py, pyansys/rst.py, tests/conftest.py, tests/test_binary_reader.py, tests/test_mapdl.py, tests/test_post.py
The upcoming 2021R1 release contains the `mapFlag` value within fdresu.inc, indicating that there are now two formats for writing index vectors for element types, real constants, coordinate systems, and sections.  This has been updated accordingly along with some minor changes to the archive reader.
Bumps to ``pyansys=0.44.20``.
=> Update for v211 (2021R1)

pyansys/_version.py, pyansys/mapdl.py, pyansys/mapdl_corba.py, pyansys/rst.py, tests/conftest.py
This PR fixes a MAPDL CORBA collection bug whereby on when attempting to collect an exited instance of MAPDL CORBA, Python repeately tries to exit an already exited server, locking the instance.  Resolves #320
By default the result writer saves the ``linear_copy`` of the unstructured mesh of result.  This causes issues when `meshio` expects the number of points to match the cell type.  `pyansys` now always saves the quadratic file.  Resolves #322.
=> Fix rst to VTK and MAPDL Collection

ansys/mapdl/core/launcher.py
use AWP_ROOT family of envvars when possible, on Windows
=> finding install dirs in non-standard locations

.github/workflows/ci-build.yml, docs/source/_static/css/ansys.css
This PR patches the `ci-build.yml` documentation deployment step when tagged.  Previously, home built step triggers additional unnecessary CI and is overly complicated.  This PR proposes using `JamesIves/github-pages-deploy-action` instead as in DPF-Core and DPF-Post.
Also, like DPF-Core and DPF-Post, this PR implements a white menu when the doc page is narrow enough to obscure the section titles in the navbar.  The Ansys css modifications to the pydata theme makes the nav-bar black, making this change necessary to use the menu.
=> Fix menu and push docs using github action

ansys/mapdl/core/_version.py, ansys/mapdl/core/convert.py, ansys/mapdl/core/examples/downloads.py, ansys/mapdl/core/launcher.py, ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mapdl_grpc.py, ansys/mapdl/core/parameters.py, docs/source/user_guide/convert.rst, docs/source/user_guide/launcher.rst, docs/source/user_guide/mapdl.rst, docs/source/user_guide/mapdl_examples.rst, tests/test_console.py, tests/test_convert.py, tests/test_corba.py, tests/test_launcher.py, tests/test_mapdl.py, tests/test_misc.py
This PR fixes a potential bug with imports with:
```py
import ansys.mapdl.core as pymapdl
```
by changing it to:
```py
from ansys.mapdl import core as pymapdl
```
There is some unexplained behavior with the first import style occurring on certain configurations, and to make it platform/environment independent, the `from ... import` is employed with this PR.
=> Fix ambigious imports

ansys/mapdl/core/_version.py, ansys/mapdl/core/mapdl.py, tests/test_mapdl.py
This PR corrects a bug where the following error is mis-reported by Python:
```py
*** ERROR ***                           CP =      64.000   TIME= XX:XX:XX
Element 1 (PLANE182) is turning inside out.
```
This PR also adds the ability to ignore errors when setting ``mapdl.ignore_errors = True``:
```py
mapdl.ignore_errors = True
mapdl.a(0, 0, 0, 0)  # normally raises an error
```
Bumps version to 0.57.5
=> add ability to ignore errors

.gitignore, ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mapdl_grpc.py, setup.py
Implement health checking.  While we don't actually do much server-side handling of the status, merely adding this health check service will inform the user if you loose connection with MAPDL.  This is a huge plus as you don't actually have to send a command to get the status of the server.
As it's going to be implemented in 2021R2, this feature has a huge try/except that handles the `NOTIMPLEMENTED` status.
=> Feature: Health Check

setup.py
It is now necessary to manually specify ﻿the version of `protobuf` used since we now require health checking within `ansys-mapdl-core`.
=> specifiy protobuf ver

ansys/mapdl/core/launcher.py
#354 pointed out that the name of the module is invalid.
=> Use ansys_corba instead of ansys-mapdl-corba

ansys/mapdl/core/mapdl_grpc.py, setup.py
Internal testing shows health check to be unable with MAPDL development version.  Disabling check by default, but leaving method included in source.
Move imports to within the health check method.  Lazy imports can be an anti-pattern, but in this case it's useful as we avoid loading the health check module upon loading the package.  Improves load time, reduces possibility of running into import issues.
Unit testing will reveal faults if/when health check is fully implemented server-side.
=> Disable health check

ansys/mapdl/core/_version.py, ansys/mapdl/core/launcher.py, ansys/mapdl/core/mapdl_console.py, ansys/mapdl/core/misc.py, docker/README.md, setup.py, tests/conftest.py, tests/test_pool.py
This PR makes `mapdl_grpc` compatible with ANSYS elastic licencing.  Removing `pexpect` under Linux was necessary as the output is slightly different when using it locally.
Adds minor documentation fixes and bumps the version to a "development version".
=> Improve Elastic Licencing Compatibility 

.ci/azure-pipelines.yml
Our builds fail sometimes on the "Pull, launch, and validate MAPDL service".  Issue arises from `tail -f` of a non-existant logging file.  For more details see:
https://dev.azure.com/pyansys/pyansys/_build/results?buildId=753&view=results
Simple fix is to touch `log.txt` to ensure the file exists, but and to also add `--reply` to give tail a few extra chances to check if the file exists.
=> Fix logging on MAPDL task

ansys/mapdl/core/launcher.py, ansys/mapdl/core/mapdl_grpc.py
This PR reverts part of the launcher to permit Python to pass I_MPI_SHM_LMT=True to MAPDL.  This corrects a problem on Ubuntu that causes MAPDL with DMP to fail to launch.
=> Fix Launcher for Linux

ansys/mapdl/core/launcher.py, ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mapdl_grpc.py, examples/00-mapdl-examples/3d_notch.py, tests/conftest.py, tests/test_launcher.py
This PR improves the detection of DMP vs. SMP when running in gRPC mode.  Prior to this PR, SMP mode was mis-reporting as being in DMP, which results in not being able to find distributed result files prior to `FINISH`.
Also improves version detection for non-default paths.
=> Better detection of smp/dmp

ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mapdl_functions.py, tests/test_grpc.py
Append NOSTART based on feedback from #380.  Includes an additional test for this.
On MAPDL server side, will ensure that commands from an input file with `/CLEAR` have NOSTART appended.
=> Append NOSTART to /CLEAR even when run as string

README.rst, ansys/mapdl/core/launcher.py, ansys/mapdl/core/mapdl_grpc.py, docs/source/conf.py, docs/source/index.rst, docs/source/user_guide/mapdl.rst, requirements_docs.txt
Ansys paths used to be capitalized in older versions of Ansys (e.g. ansys vs ANSYS) and the `_version_from_path` reports being unable to extract the path.
This PR fixes this and includes additional documentation based on user feedback when installing MAPDL on Ubuntu.
=> Fix Version casematch

ansys/mapdl/core/launcher.py, ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mapdl_grpc.py, docs/source/user_guide/mapdl.rst, tests/test_launcher.py
Resolves #390 and #389 by correcting the documentation on `load_array` noting the shift to ``parameters``.
When resolving #390, identified the GUI will launch properly, but will fail to return to the console in certain cases.  A timeout for `_launch` was added along with correct treatment of "Begin Level" vs "BEGIN" for SMP vs. DMP.
=> Fix load_array docs and GUI launcher

ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mapdl_grpc.py
Multiple instances of MAPDL using `_flush_stored` will fail to write/read to the same file due to permission errors.  This PR writes to a random tmpfile name as well as removes that file when when finished.
=> use random filename when flushing in grpc

ansys/mapdl/core/io_commands.py, ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mapdl_functions.py, ansys/mapdl/core/mapdl_grpc.py, ansys/mapdl/core/parameters.py, tests/test_mapdl.py
This PR improves the stability of the parameter array setter.  The `*DIM` command was moved within `non_interactive`, providing a slight improvement to performance as well.
Additionally, it was discoverd that `PARRES` runs `\INPUT` under the hood, leading to the too many nested `/INPUT` error.  This PR also moves that command into a new `_MapdlIoCommands` class to protect the gRPC/CORBA server.
=> Improve parameters setter stability

ansys/mapdl/core/pool.py
Simple PR to improve pool stability by clearing via `mute=True`.
=> mute output from finish and clear from server

README.rst
Changed the broken Examples link in the main README.rst to the one given in [issue 407](https://github.com/pyansys/pymapdl/issues/407)
=> Broken examples link fix

ansys/mapdl/core/mapdl.py
As noted in #416, when the MAPDL directory contains `'\n'`, those fail to be replaced.  This resolves #416 using inputs from @natter1
=> fix path edge case

tests/conftest.py, tests/test_pool.py
Resolve #430 to deal with mixed slash/backslashes in path in `conftest.py`.
=> clean up path and fix pool testing

ansys/mapdl/core/mapdl_functions.py, tests/test_mapdl.py
Resolve #435 by addint in the missing parameter.  Also adds in basic unit testing, documentation, and improved handling of ``bool`` parameters.
=> clean up coriolis method

ansys/mapdl/core/_commands/database/components.py, ansys/mapdl/core/_commands/database/coord_sys.py, ansys/mapdl/core/_commands/database/selecting.py, ansys/mapdl/core/commands.py
Added examples to commands based on the lectures 1-6 in the MAPDL
lecture course. The commands have been converted to pymapdl from raw
APDL. They have not been tested where the commands obviously line-up
with what they should be (they all follow what the documentation says 
they should do, so they should work fine).
This PR is based on lectures 1-6. There are 21 lectures in total and I am slowly
working through them all. Do not delete this branch as I will use it for future 
PRs on the same topic.
=> Added examples to multiple commands

LICENSE, setup.py
Due to recent changes in pyvista themes, require `matplotlib` for theme setting.  This will be necessary when setting themes within pymapdl.
=> Add matplotlib to imports

setup.py
Due to updates with `pip`, users can get into a near endless install when trying to `pip install ansys-mapdl-core`.  Setup now performs basic checks to verify python version (i.e. 64 bit < Python 3.8)
=> Check python version on install

doc/make.bat, doc/source/contributing.rst
This PR resolves #501 by adding back in the batch build file and renames all mentions of  ``docs --> doc``.
Some background:
The directory `docs` was renamed to `doc` to match several popular open source projects like `numpy` and `scipy`.  I failed to update the docs and the batch file was lost when the directory was renamed.
=> docs --> doc

ansys/mapdl/core/mapdl.py
Closes #535.
Backwards compatibility maintained, but improved syntax available. I'm not sure if more needs to be done to bring in line with the docs, however.
=> added method to fetch query class instance to mapdl

ansys/mapdl/core/mapdl.py, doc/source/user_guide/mesh_geometry.rst, examples/00-mapdl-examples/mapdl_beam.py, examples/00-mapdl-examples/statically_indeterminate_reaction_force_analysis.py, ignore_words.txt, requirements_style.txt, tests/test_mapdl.py
The `nplot` method uses the `knum` rather than the nnum parameter when plotting nodes.  Changed to ``nnum``.
=> Fix nplot parameters

ansys/mapdl/core/launcher.py
Resolve #564 by fixing the documentation for additonal switches in the launcher docs.﻿
=> fix additional switches doc

requirements_docs.txt
Minor change to the doc build req to remove the `Jinja2` version.
=> remove Jinja2 ver req

doc/source/api/post.rst, doc/source/user_guide/post.rst, examples/00-mapdl-examples/contact_elements.py, requirements_docs.txt
This PR fixes the version of sphinx for the docbuild to `sphinx==4.0.3` to fix the missing logo.  As of `sphinx==4.1.2` this has not been fixed.
Also:
=> Fix missing logo

.github/workflows/smoke-tests.yml, setup.py
It's been a long time coming, but Python 3.9 is finally supported as of this PR.
Also adds smoke tests to make sure we can import on the supported versions.  Assumption that server behavior is identical regardless of the environment (which isn't the best assumption and we're working on getting windows agents with MAPDL).
=> Support 3.9

tests/common.py, tests/conftest.py, tests/test_console.py, tests/test_corba.py, tests/test_grpc.py, tests/test_mapdl.py
This PR fixes our CI/CD where `test_grpc.py` was being skipped because MAPDL wasn't installed.  We now override that flag by also checking if gRPC specific environment variables have been setup.
=> allow HAS_GRPC when running on devops

.ci/azure-pipelines.yml, .github/workflows/ci-build.yml, .github/workflows/nightly-doc-build.yml, ansys/mapdl/core/_commands/solution/analysis_options.py, ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mapdl_grpc.py, ansys/mapdl/core/post.py, doc/source/user_guide/mapdl.rst, docker/mapdl/IMAGE_NAME, docker/mapdl/reduce_mapdl.py, tests/test_grpc.py, tests/test_mapdl.py
Resolves issue #571 by wrapping CMATRIX internally using `non-interactive`.  CMATRIX within MAPDL redirects the server output and simply running `mapdl.run('cmatrix...') will work.
=> Wrap CMATRIX for gRPC

ansys/mapdl/core/mapdl_grpc.py, doc/source/user_guide/mapdl.rst, tests/test_grpc.py
This PR raises the maximum receive message length to 256 MB based on https://stackoverflow.com/questions/42629047/how-to-increase-message-size-in-grpc-using-python and suggestions from @germa89 in #578.
I figure that 256 MB is a sensible limit, but this can be overridden with ``PYMAPDL_MAX_MESSAGE_LENGTH``.  Docs are also updated.
Resolves #578.
﻿
=> Raise max gRPC receive limit to 256MB

.flake8, .github/workflows/style.yml, .gitignore, Makefile, ansys/mapdl/core/inline_functions/nearest_queries.py, ansys/mapdl/core/inline_functions/normals_queries.py, ansys/mapdl/core/launcher.py, ansys/mapdl/core/mapdl_geometry.py, ansys/mapdl/core/mapdl_grpc.py, ansys/mapdl/core/post.py, examples/00-mapdl-examples/2d_plate_with_a_hole.py, examples/00-mapdl-examples/3d_notch.py, examples/00-mapdl-examples/mapdl_3d_beam.py, examples/00-mapdl-examples/mapdl_beam.py, examples/00-mapdl-examples/vm-004-deflection_of_a_hinged_support.py, examples/03-tips-n-tricks/03-using_inline_functions_and_Query.py, requirements_style.txt, tests/test_inline_functions/test_query.py, tests/test_inline_functions/test_selection_queries.py, tests/test_launcher.py, tests/test_mapdl.py, tests/test_math.py
This is the first PR to introduce flake8 to enforce PEP8 guidelines. The flake8 configuration is defined in the `.flake8` file. Running flake8 was added as part of the style CI process.
This PR addresses issues with blank lines, indentations, and whitespace corresponding to error codes W391, E115, E117, E122, E124, E125, E225, E231, E301, E303, F403. There are still more error codes to address in following PRs.
=> Introduce flake8 style guidelines

.flake8, ansys/mapdl/core/_commands/database/selecting.py, ansys/mapdl/core/_commands/graphics_/style.py, ansys/mapdl/core/_commands/post1_/element_table.py, ansys/mapdl/core/_commands/post26_/setup.py, ansys/mapdl/core/_commands/preproc/element_type.py, ansys/mapdl/core/_commands/preproc/explicit_dynamics.py, ansys/mapdl/core/_commands/preproc/status.py, ansys/mapdl/core/_commands/preproc/volumes.py, ansys/mapdl/core/_commands/solution/analysis_options.py, ansys/mapdl/core/_commands/solution/birth_and_death.py, ansys/mapdl/core/examples/examples.py, ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mapdl_types.py, ansys/mapdl/core/parameters.py, docker/mapdl/reduce_mapdl.py, examples/02-geometry/04-primitives.py, examples/03-tips-n-tricks/03-using_inline_functions_and_Query.py, examples/03-tips-n-tricks/04-rotational-displacement.py, tests/common.py, tests/test_console.py, tests/test_corba.py, tests/test_launcher.py, tests/test_mapdl.py, tests/test_misc.py, tests/test_post.py
Organizes imports and removes any unused module imports. Adds extra directives to flake8 config after black formatting.
=> Additional flake8 standards

ansys/mapdl/core/launcher.py
`launch_mapdl` fails outright due to an invalid parameter name.
This is a reminder to self that we need to implement some sort of windows CI.  As much as I don't want to pay for a build machine, we might have to.  I might borrow the one used for AEDT since they're not at 100% usage.
=> Fix parameter name in `launcher.py`

setup.py
Simple PR to resolve #618 by adding a syntax error within our setup requires.  Surprising that twine and CI didn't pick up on this but conda did.
=> fix setup req

tests/test_console.py
Simple fix to remove a the duplicate fixture `cleared` within `test_console`.
=> remove duplicate cleared fixture

ansys/mapdl/core/mapdl.py
An unintended (or unintentional) side effect of the file logger is that the log file is created for each and every run of pymapdl.  While I appreciate the log, it's often unneeded and we can't control its location.
Removing this for now and requesting that we instead either add it to the launcher, or better, add it as a method to the `Mapdl` class to control both the level of the handler and the location of the file.
=> remove file logging

ansys/mapdl/core/licensing.py
Some testing on a recent install with AEDT revealed that the Ansys license utility in `ansysli_util_path` in ``checkout_license`` may or may not be installed in `shared_files` (or `Shared Files` on Windows).
This PR disables the check by default to avoid a false negative if unable to locate the license utility and MAPDL fails to start.  License file appears unaffected.
=> disable default license checkout on LicenseChecker

tests/test_licensing.py, tests/test_mapdl.py
This PR fixes the following tests:
- Unit tests were failing on linux due to changed defaults on the license checker.  Simple patch.
- `test_cdread_in_python_directory` was creating a temporary file `model.cdb` in the current working directory. Test behavior has been fixed.
Pinging @german89
When creating files, avoid assuming anything regarding paths and always use the `tmpdir` fixture.  This fixture creates temporary directories and provides a convenient way of creating files on the fly without modifying the user's environment.
In the case of `test_cdread...`, we were testing if a file within the current working directory of Python would be seen by pymapdl and then copied over (or used directly if local).  Rather than creating the file in the current working directory (which would have …
=> licensing and tmp file fixes

ansys/mapdl/core/_commands/session/run_controls.py
Encountered a minor issue with local testing with `Mapdl.cwd`: When passed a `Pathlib.Path`, the test fails outright.  A simple fix is to always convert to string before executing the path when checking the string.
Also added a minor example.
=> convert path to string in CWD

doc/source/conf.py
Simple change to navigate to the main pyansys documentation page when clicking the logo.
=> naviage to main page on clicking logo

README.rst
Fix the link from the github actions badge.
=> Fix github actions badge link

doc/source/user_guide/extended_examples/Python_UPF/python_upf_examples.rst, doc/source/user_guide/extended_examples/index.rst, doc/source/user_guide/extended_examples/techdemo-1/ex_0-tecbrakesqueal.rst, doc/source/user_guide/index.rst, doc/source/user_guide/upf.rst
Requested to add the Python UPF to the documentation, as well as the examples.
Fix #702
Closes #702
=> Adding Python UPF documentation and examples

ansys/mapdl/core/convert.py, tests/test_convert.py
Implement a logger on the converter script. 
The logger is quite simple. Basic stdout output. No format. Uses the standard ``logging`` module.
The logging is made when we append the line to ``FileTranslator.lines`` through an overloaded ``append`` method in a custom ``List`` class.
If the optional keyword ``show_log`` is ``True`` in ``FileTranslator``, the resulting converted PyMAPDL is printed to the stdout.
```python
>>> from ansys.mapdl.core.convert import convert_apdl_block, FileTranslator
>>> apdl_ = """FINISH
... /PREP7
... """
>>>
>>>_ = convert_apdl_block(apdl_strings=apdl_, line_ending='\n', show_log=True)
Converted: '"""Script generated by ansys-mapdl-core version 0.60.dev0"""'
Converted: 'from ansys.mapdl.core import launch_mapdl'
Converted: 'mapdl = …
```
=> implement logger in convert_script

ansys/mapdl/core/_commands/parse.py, ansys/mapdl/core/_commands/preproc/booleans.py, ansys/mapdl/core/_commands/preproc/volumes.py, ansys/mapdl/core/post.py, examples/00-mapdl-examples/pressure_vessel.py
Fix ``aadd`` method for Windows (currently fails), and now returns the correct int type.
Add pressure example, thanks to @aliirmak in #729.
=> add pressure vessle example

ansys/mapdl/core/launcher.py, ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mapdl_console.py, ansys/mapdl/core/mapdl_corba.py, ansys/mapdl/core/mapdl_grpc.py
The argument type wasn't consistent across documentation and code, mixing file mode and Booleans.
Now that parameter will accept strings, which will be the name of the file (located then in the python working directory) or the full path of it. 
Fix #742 
Closes #742
=> Fix mixed argument types in ``log_apdl`` argument.

ansys/mapdl/core/mapdl_geometry.py
As mentioned in #745 , when using ``ninc`` and/or ``na2``, the command ``mapdl.aplot`` does not plot all the areas it should be. 
Removing overwritting of ``amax``.
Removing equal lenght of groups and grid check. This does not apply if we are not selecting all areas.
Closes #745 
Fix #745
=> Fix/Aplot not working when using ``amax`` and/or ``ainc``

ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mapdl_grpc.py, pytest.ini, tests/test_grpc.py
Resolve #748 by implementing a basic guard when using ``non_interactive`` to avoid simultaneous querying the gRPC server.
=> add get_value guard when using non_interactive

.github/workflows/ci.yml, ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mesh_grpc.py, tests/test_mapdl.py
Resolves #751 by adding in an additional check within `MeshGrpc` to ensure that hidden nodes are not added to the internal `mapdl.mesh.grid` object when pulling the nodes from the server.  For reference, these hidden nodes are created for BEAM188 elements when running `SOLVE`. Oddly enough, MAPDL will mention that these nodes exist in `CDWRITE`, but not actually write them, nor list them when running `mapdl.nlist`.
---
Our style check was running the spell check twice. This has been split up into two separate tasks, and the requirements are also installed in a previous step so it's easier to read the logs.
=> account for edge case with hidden nodes

tests/test_mapdl.py
I have seen that test units for ``load_table`` and ``load_array`` fail from time to time. I believe it is related to being very exigent regarding the ``np.allclose`` tolerance. 
This PR relaxes the Numpy relative tolerance, so it should be more robust now.
=> Fixing error tolerance in `load_table` and `load_array`

tests/test_mapdl.py
Ping @germa89:
Looks like #758 didn't quite resolve our issues. We're still seeing intermittent failures in `test_load_array`. You can validate this locally with:
```
pytest tests/test_mapdl.py -k test_load_array --count 100 -x
```
This fails because when our input array is shaped `(10, 1)`, MAPDL will output a flat array `(10,)`. Since numpy outputs flat arrays when the second dimension is 1, (e.g. `numpy.arange`), this PR changes the test to account for this edge case.
If we want to test for a variety of edge cases, use parameterized inputs:
```py
@pytest.mark.parametrize("dimx", [1, 3, 10])
@pytest.mark.parametrize("dimy", [1, 3, 10])
def test_load_array(mapdl, dimx, dimy):
my_conv = np.random.rand(dimx, dimy)
mapdl.load_array("my_conv", my_conv)
if dimy == 1:
my_conv = my_conv.ravel() …
```
=> Use consistent tests

ansys/mapdl/core/check_version.py, ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mapdl_geometry.py, ansys/mapdl/core/mapdl_grpc.py, ansys/mapdl/core/mesh_grpc.py, ansys/mapdl/core/parameters.py, doc/source/user_guide/mapdl.rst, tests/test_mapdl.py
Chained commands are fully supported by MAPDL, especially in distributed mode:
> Multiple commands entered in an input file can be condensed into a single line if the commands are separated by the $ character (see Condensed Data Input in the Command Reference). Distributed Ansys cannot properly handle condensed data input. Each command must be placed on its own line in the input file for a Distributed Ansys run.
This PR depricates the usage of ``chain_commands`` internally, but still leaves the method available for those who wish to use it in shared memory parallel.
=> depricate usage of chain_commands

ansys/mapdl/core/mapdl.py
@RomanIlchenko1308 identified that the `color` parameter isn't working for `aplot` or `vplot`. This PR corrects the behavior and also correctly sets the default coloring for the area plotting to be a fixed color (rather than defaulting to the area numbering).
=> allow color parm for area plotting

ansys/mapdl/core/mapdl.py
=> added type hint for the result property fixing #768

ansys/mapdl/core/post.py
Fix #723 by improving the parsing of the output string in `mapdl.post_processing.time_values()`.
Now all the heavy lifting is done by `np.genfromtxt` and no format issued. However, for this specific case, the format is fixed using `mapdl.header` and `mapdl.format`.
=> Fix parsing time values in `post_processing` module

ansys/mapdl/core/mapdl_grpc.py, tests/test_mapdl.py
`/TBFT` does now upload the experimental data files. Close #725
=> Improved /TBFT function.

ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mapdl_grpc.py
Close #794 by using ``log_file`` keyword argument to add a file handler.
=> Fix/ ``log_file`` keyword was not being used in ``_Mapdl``

doc/source/user_guide/launcher.rst
=> Doc/ Adding 'exec' keyword info to documentation

ansys/mapdl/core/launcher.py, ansys/mapdl/core/logging.py, ansys/mapdl/core/mapdl.py, tests/test_mapdl.py
Resolve #800 by removing the additional reference to the mapdl instance in `ansys/mapdl/core/logging.py`.
@germa89, note that adding `self.extra = extra` created an additional reference to our mapdl instance, which then created a circular reference since our mapdl instance contained a reference to the logger, which contained a reference to the mapdl instance.
Once this is merged, let's plan to push a release.
=> Fix MAPDL collection

.github/workflows/ci.yml, .github/workflows/nightly-doc-build.yml, .github/workflows/nightly-mapdl-check.yml, doc/source/conf.py, doc/source/index.rst
Authorize using an application rather than a GH PAT.
This fixes #797, and also makes it possible to automate our release of documentation for [PyMAPDL Documentation](https://mapdldocs.pyansys.com/) to https://github.com/pyansys/pymapdl-docs.
Misc Changes
- Use port 21000 for MAPDL docker container due instability with 32771. Should the port keep breaking, we're going to implement an open port ID tool.
- Fix PDF documentation artifact upload.
- Dynamic date for copyright and version in the documentation.
=> Fix doc build auth

.github/workflows/ci.yml, doc/Makefile
Release documentation build for v0.60.4 broken. This PR should fixs it by moving the PDF build step after the initial html build step.﻿
Additionally, this adds a manual upload step to overwrite broken release docs. Usage is `make -C doc html deploy`
=> fix release doc build

ansys/mapdl/core/inline_functions/scalar_queries.py
Updated temperature example, but still need to fix temperature description
=> Updated temperature example

ansys/mapdl/core/commands.py, tests/test_commands.py
Fixes issue for #830 by using regular expressions. There's a small cost in efficiency but great improvement in robustness by using regular expressions when parsing the tabular output.
=> improve robustness of CommandListingOutput

ansys/mapdl/core/inline_functions/inline_functions.py, ansys/mapdl/core/inline_functions/scalar_queries.py, tests/conftest.py, tests/test_inline_functions/test_field_component_queries.py
Created equivalent pymapdl commands for the 4 scalar queries: MAG, PRES, VOLT,
and TEMP. Examples have only been added for one of the four and tests
for none of them because my knowledge of APDL is not extensive enough.
Further work will require external input.
@rgpatchi Can you create the examples for the commands without them? In addition we can work on tests for the three new functions together.
=> Created api commands for mag, pres and temp and volt

docker/README.md
Docker has migrated to the container registry, see [Migrating to the Container registry from the Docker registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry). This PR updates the docs accordingly.
=> Fix docker readme

ansys/mapdl/core/__init__.py, ansys/mapdl/core/jupyter.py
Modify `jupyter.py` to work with changes from `ansys-jupyterhub-manager`. Specifically, assembly and execution of the spawning of MAPDL is offloaded and resonsibility is limited to instantiating MAPDL.
=> make jupyter.py compatible for upstream ansys-jupyterhub-manager

.github/workflows/nightly-mapdl-check.yml
Do not run on push and PR as latest image may be invalid.
Resolves #851.
=> only run latest validation nightly

ansys/mapdl/core/commands.py
Fix conversion to dataframe issue by making sure a correct parsing in `to_list()` method.
`to_dataframe()` method in `BCListingOutputCommand` is broken because of a bad format output in `to_list`.
**Current to list**
```python:
>>> outlist = out.to_list()
[[[(...)]],[[(...)]],...]
>>> outlist[0]
[('1', 'UX', '0.00000000', '0.00000000')]
```
The tuple is unnecessary.
Basically:
If we use `findall` in a line, we should retrieve the first item if exist:
```python
def _parse_table(self):
"""Parse tabular command output."""
parsed_lines = []
for line in self.splitlines():
if line:
items = BC_REGREP.findall(line)
if items:
parsed_lines.append(list(items[0]))  #Here!
```
Also, this problem was not caught by CI/CD because at the moment pandas is optional library and because of that, we do not …
=> Fixing BC parsing issue

requirements_test.txt
=> Adding pandas to test requirements

ansys/mapdl/core/mapdl.py, tests/test_mapdl.py
The PR #840 broke this. 
This was not catch by CICD because those test do not run on CICD. Not sure why.
=> Fixing ``CWD`` and failing tests

doc/source/getting_started/running_mapdl.rst
Fix a typo in one of the title in "Getting Started" documentation section.
=> Improve the "Getting Started" documentation section.

ansys/mapdl/core/_commands/session/list_controls.py, ansys/mapdl/core/convert.py, ansys/mapdl/core/launcher.py, ansys/mapdl/core/mapdl.py, ansys/mapdl/core/mapdl_console.py, ansys/mapdl/core/mapdl_corba.py, ansys/mapdl/core/mapdl_grpc.py, doc/source/user_guide/convert.rst, tests/test_commands.py, tests/test_convert.py, tests/test_mapdl.py
I feel it could be useful to have the `/COM` commands printing also the python console.
I'm aware this might not be the greatest feature ever and it will not be used that much, but I feel it can be useful.
For example, for the ``ds.dat`` files which are converted from Mechanical, it is useful to print this ``/COM`` output, so we know for example in which stage of the execution we are in, without having to add manually prints.
I coded this feature to be disabled by default in Mapdl execution but it will be default in the converted (I guess MAPDL people will appreciate having this kind of input).
This feature can be activated at any moment by editing the appropriate property: ``mapdl.print_com``. 
See unit test for an example.
=> Print ``/COM`` to python console

ansys/mapdl/core/mapdl.py, tests/test_mapdl.py
``*GET`` command gives empty response if we are using it after ``NOPR``, of course this should be the case, everytime we issue a ``NOPR`` we should ensure a ``GOPR`` follows up. However I find difficult to track this in the converter module, hence I'm checking the state of the printout before issuing ``*GET`` command.
We should probably consider to get rid of this old implementation of "*get", by getting the parameter value using grpc API instead of parsing output.
=> Check printout option before using get

ansys/mapdl/core/plotting.py, tests/test_console.py, tests/test_corba.py, tests/test_mapdl.py, tests/test_post.py
Close #863 by implementing ``return_cpos`` optional keyword.
I also added the option that if no output is request, it will return ``None``. I think it is more pythonic.
=> Return camera position is optional in general plotter

ansys/mapdl/core/_commands/solution/miscellaneous_loads.py, tests/test_mapdl.py
Adding missing arguments to RESCONTROL and reformatting docstring.
=> Adding missing arguments to RESCONTROL

ansys/mapdl/core/mapdl.py, tests/test_mapdl.py
Surprisingly there is a 7th hidden argument in ``*get``, and as far as I know (I should research it a bit more) it is only for including internal nodes in the ``*get`` calculations.
The following line is totally correct:
```
*get, _MAXNODENUM, node, 0, NUM, MAX,,,INTERNAL
```
However, that ``INTERNAL`` parameter is not documented anywhere, but it is used to output ``ds.dat`` files.
Funny part, it is that previous line will ouput:
```
*GET  _MAXNODENUM  FROM  NODE  ITEM=NUM  MAX   VALUE=  425.000000     \n  (INCLUDE INTERNAL NODES)
```
which our ``mapdl.get`` method will parse to:
```
425.000000     \n  (INCLUDE INTERNAL NODES)
```
Hence I'm making something to crop the rest of the text. Not sure what to do with the ``(INCLUDE INTERNAL NODES)`` part.
I guess if someone is using that …
=> Adding extra argument to ``*get``

ansys/mapdl/core/_commands/session/list_controls.py, tests/test_mapdl.py
If ``mute`` is activated in any of its ways (using ``kwarg`` or ``mapdl.mute``), the ``/COM`` commands are not printed to python console.
=> Linking ``mapdl.print_com`` behavior to ``mapdl.mute``

.github/workflows/ci.yml, .github/workflows/nightly-doc-build.yml, .github/workflows/nightly-mapdl-check.yml
As the title.
I thought an email will be more useful, but
- it is difficult to setup an outlook email because of the 2FA
- We will need an email address for the project?
So, although I'm not big fan of MS Teams, let's give it a try.
=> Send a MS Teams notification if nightlies (MAPDL or docs) fails

ansys/mapdl/core/_commands/preproc/database.py, ansys/mapdl/core/mapdl_grpc.py, tests/test_mapdl.py
Close #879 by fixing the ``CDREAD`` argument mess. It also improve the test cases and doc string (format).
=> Fix ` CDREAD` arguments

ansys/mapdl/core/mapdl.py, tests/test_mapdl.py
As the title.
I also added unit tests for the apdl logger.
=> Fix wrong string argument in APDL logger

doc/source/getting_started/index.rst, doc/source/getting_started/using_julia.rst
=> Adding Julia documentation

codecov.yml
This PR "improves" coverage by ignoring most of our commands section.
Note: We're doing intergration testing right now, which I think should still be run in our CI/CD, but we also should consider doing actual unit testing through a mocked Mapdl application.
=> Improve coverage

.github/dependabot.yml, requirements_test.txt
This PR adds dependabot for our CI/CD. We have pinned requirements for our doc build, this pins our testing requirements as well.
=> Add dependabot

.github/workflows/ci.yml
Quick fix for our dependabot PRs. We only need the application token for tags, and dependabot will never tag.
=> do not get application token unless deploying

.github/workflows/ci.yml, setup.py
Python 3.6 is in end-of-life support. Hence we are deprecating any CICD related.
=> Removing python 3.6

ansys/mapdl/core/plotting.py
Closes #922 by recreating returning parameters before exiting the `general_plotter` function.
=> Updating returning parameters because of cpos

doc/source/getting_started/index.rst, doc/source/getting_started/wsl.rst
For the moment, the WSL guide seems application specific to MAPDL. Until we have documentation for Fluent, let's move it here.
See https://github.com/pyansys/dev-guide/pull/51 for where it's being moved out of.
=> Add WSL guide

.coveragerc, ansys/mapdl/core/mapdl_grpc.py, doc/source/user_guide/mapdl.rst, tests/test_grpc.py, tests/test_mapdl.py
Close #926 by implementing new behaviors for `mapdl.download`:
```py
mapdl.download('all')  # All simulation files, meaning files ending in 'out', 'full', 'rst', 'cdb', 'err', 'db', or 'log'
mapdl.download('everything')  # **Every single file** in the working directory.
mapdl.download('*.log')  # Every file which extension is 'log'. Uses global pattern.
mapdl.download('file.txt')  # Download 'file.txt'. Standard used behavior.
mapdl.download(['file0.txt', 'file0.rst']) # Download a list of files. Accept list of strings or tuple of strings.
```
- Sure the labels could be improved. 'all' and 'everything' seems repetitive. But 'all' is a standard so I don't think it should include every single file in the MAPDL working directory. There many files there... batch, esav, mode, etc which I don't …
=> Expand download options

.github/workflows/nightly-doc-build.yml
The nightly doc building was failing because of the changes in the requirements files, now they are located in the requirements directory.
I'm just re-pointing them to the right file.
This was caught with the help of the teams notification.
=> Fixing requirements installations

.github/workflows/nightly-doc-build.yml
The nightly doc building was failing because of the changes in the requirements files, now they are located in the requirements directory.
I'm just re-pointing them to the right file.
This was caught with the help of the teams notification.
=> Fix nightly doc build

src/ansys/mapdl/core/_commands/database/selecting.py, tests/test_mapdl.py
Close #945 by fixing an error in the cmd string generation.
=> Fix `SELTOL` always resetting to default values

README.rst, src/ansys/mapdl/core/mapdl_grpc.py, src/ansys/mapdl/core/math.py, tests/test_math.py
Closes #930 by adding function to automatically upload files to MAPDL instance working directory.
=> Math module file uploader

src/ansys/mapdl/core/parameters.py
Increase the format in the MWRITE command.
This was giving some errors when the number was higher than 1E7.
=> Increasing the format for printing numbers in _get_parameter_array

src/ansys/mapdl/core/_version.py, tests/test_mapdl.py
=> Matching _version file to toml project.

.github/workflows/ci.yml, codecov.yml
Using cache to avoid running all the examples every time we do push/PR
Close #951
=> Using cache when building documentation

src/ansys/mapdl/core/mapdl_grpc.py, src/ansys/mapdl/core/parameters.py, tests/test_parameters.py
Close #952 by implementing an iterative process.
Ok, it might be slow sometimes, but I think it is a reasonable approach for this case. I setup an upper limit at `F60.12` for the float format.
=> Flexible number format in `_get_parameter_array`

src/ansys/mapdl/core/mapdl.py
The string `level`: The right method is `upper`.
=> mapdl.add_file_handler: correct lever.upper()

src/ansys/mapdl/core/mapdl.py
The object `self._log` if (type `PymapdlCustomAdapter`) has no method `addHandler`, it is in `self._log.logger` (type `Logger`).
=> Fix mapdl: _log.logger.add_handler

src/ansys/mapdl/core/math.py, tests/test_math.py
I realised that in local mode this was failing. 
Unfortunately all our test units are designed for non local. So this was not caught at the moment.
=> Fix load file in local mode

pyproject.toml, src/ansys/mapdl/core/math.py
This PR updates our dependencies to use the latest gRPC interface package `ansys-api-mapdl`, which has been renamed from `ansys-api-mapdl-v0` and updated to `v0.5.1`.
This opens up the usage of the database service API.
=> Use latest grpc package

src/ansys/mapdl/core/_commands/preproc/materials.py, src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/math.py, src/ansys/mapdl/core/misc.py, tests/test_mapdl.py
Close #975 by using `/INPUT` instead of `/MPREAD`.
I also included the `load_file` from the Math module, which is now moved to `misc` module. Ideally we should merge it with the `_get_file_path` in mapdl_grpc.
This have some side effects:
- "LIB" option cannot be used.
- You cannot import material library files from a location different than the one you are including in the `/INPUT`.
=> Fix MPREAD not having effect

src/ansys/mapdl/core/mapdl_geometry.py, src/ansys/mapdl/core/mesh_grpc.py, tests/test_geometry.py, tests/test_mesh_grpc.py
I have noticed that MAPDL was returning errors when querying the number of entities using `vget` but there was none. This crashed the MAPDL session.
I have improved (I believe) the checks on the PyMAPDL side, so we avoid requesting those parameters using `vget` when there is no entities. 
Closes #971 
Improves #965
=> Empty mesh object instabilities

pyproject.toml, requirements/requirements_docs.txt
Not forcing any particular version, just lower bound.
This close #979 by updating pymapdl reader version.
=> Using a newer version of pymapdl reader. 

src/ansys/mapdl/core/mapdl_grpc.py, tests/test_grpc.py
Resolve #987 by allowing for instantiating `MapdlGrpc` directly from a gRPC channel.
Behind the scenes, it's still running a multi-connect and reuses much of the existing "hardware".
```py
If you wish to customize the channel, you can also directly connect
directly to gRPC channels. For example, if you wanted to create an insecure
channel with a maximum message length of 8 MB.
>>> import grpc
>>> channel = grpc.insecure_channel(
...     '127.0.0.1:50052',
...     options=[
...         ("grpc.max_receive_message_length", 8*1024**2),
...     ],
... )
>>> mapdl = pymapdl.Mapdl(channel=channel)
```
=> add direct channel feature

src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_geometry.py
Encountered a fairly alarming and cryptic error when running:
```py
from ansys.mapdl.core import launch_mapdl
mapdl = launch_mapdl()
mapdl.aplot()
```
Error traceback included being unable to update an empty geometry cache.
Area plotting now includes a basic test to verify that when there is no geometry to plot, nothing is plotted (as in standard MAPDL behavior).
=> check for empty geometry when plotting

.github/workflows/ci.yml, .github/workflows/nightly-doc-build.yml, doc/source/getting_started/docker.rst, doc/source/getting_started/wsl.rst, docker/README.md, docker/mapdl/IMAGE_NAME
Close #984 by updating all docker references to `ghcr.io`
=> Docker container location update

src/ansys/mapdl/core/math.py, tests/test_math.py
Close #990 
You can still operate with these mappings but it should be done using `mapdl.run("*SMAT....")`. This allows to work inside MAPDL with these nodes mapping. 
Also adding default `dtype` for the `get_vec` when using `BACK` and `FORWARD` since MAPDL returns ints arrays.
Also, to avoid possible errors, I'm forcing array conversion (`array.astype`) when using `get_vec` and `asarray` keyword.
=> Avoiding nodes mapping in PyMAPDL.

.github/workflows/ci.yml, .pre-commit-config.yaml
This PR checks we can run CI on the 22.1 image.
Also implements additional pre-commit checks to stop pushing to main.
=> Run CI on 22.1 image

src/ansys/mapdl/core/mapdl_grpc.py, tests/test_database.py, tests/test_grpc.py
As the title. This was showing when PyMAPDL wasn't able to connect. 
This was introduced in #996
=> Fix misspelled `_channel_str` attribute

src/ansys/mapdl/core/plotting.py
Close #1024 by changing some keyword defaults behind the scenes.
=> Changing keyword args default to avoid a savefig error.

src/ansys/mapdl/core/_commands/preproc/meshing.py, src/ansys/mapdl/core/mapdl_grpc.py
Closes #1020 by reflecting the code changes made in #928 in the `download` docstring example section.
I also add a `chunk_size` check, and fix the `VIMP` docstring.
=> Updating docstring in `download`

src/ansys/mapdl/core/launcher.py, src/ansys/mapdl/core/mapdl_grpc.py, src/ansys/mapdl/core/misc.py, tests/test_database.py, tests/test_grpc.py, tests/test_misc.py
When using any of the arguments `ip`, `port` and/or `start_instance` together with the env vars `PYMAPDL_IP`, `PYMAPDL_PORT` and `PYMAPDL_START_INSTANCE`, the environment variables have priority over the specified corresponding arguments. I believe this is not the most convenient.
The priority will be:
1. Specified argument
2. Environment variable
3. Default argument
This respond to some comments made in #1014 which will help to fix.
=> Changing priority between env_vars and args.

.pre-commit-config.yaml
Our CI on main has been failing lately due to the check to not commit to main, which fails when commits are merged to the main branch.
=> disable no-commit to main check

src/ansys/mapdl/core/_commands/apdl/array_param.py
I just stumble upon some format issues in the docstrings in `array_param` file.
Final output look nicer (sample)
=> Docstring formatting issues

tests/test_grpc.py
test_clear_nostart needed fixed for rebranding
=> update test_grpc.py for rebranding changes

src/ansys/mapdl/core/database/database.py, src/ansys/mapdl/core/mapdl_grpc.py
Fixing #965 I realized that when inspecting the `mapdl` object, some of their attributes raise an error:
- `mapdl.chain_commands`: Chained commands are not permitted in distributed ansys.
```
'Traceback (most recent call last):\n  File "c:\\Users\\gayuso\\.vscode\\extensions\\ms-python.python-2022.4.1\\pythonFiles\\lib\\python\\debugpy\\_vendored\\pydevd\\_pydevd_bundle\\pydevd_resolver.py", line 192, in _get_py_dictionary\n    attr = getattr(var, name)\n  File "C:\\Users\\gayuso\\Others_pymapdls\\pymapdl_0\\pymapdl\\src\\ansys\\mapdl\\core\\mapdl.py", line 416, in chain_commands\n    
raise RuntimeError(\nRuntimeError: Chained commands are not permitted in distributed ansys.\n'
```
- `mapdl.db`: ImportError: cannot import name `mapdl_db_pb2_grpc` from `ansys.api.mapdl.v0` .
``` …
```
=> Removing undesired command output

README.rst, src/ansys/mapdl/core/commands.py, src/ansys/mapdl/core/mapdl.py, tests/test_commands.py
I was using pymapdl and was annoyed at the printout from commands.  I would see things like this:
```
>>> mapdl.prep7()
'*** ANSYS - ENGINEERING ANALYSIS SYSTEM  RELEASE 2022 R1          22.1BETA ***\n DISTRIBUTED Ansys Mechanical Enterprise                       \n\n 00000000  VERSION=WINDOWS x64   09:29:10  APR 20, 2022 CP=      0.391\n\n                                                                               \n\n\n\n ** WARNING: PRE-RELEASE VERSION OF ANSYS 22.1BETA\n  ANSYS,INC TESTING IS NOT COMPLETE - CHECK RESULTS CAREFULLY **\n\n          ***** ANSYS ANALYSIS DEFINITION (PREP7) *****'
>
```
with this change, the printout now looks like this:
```
>>> mapdl.post1()
***** ROUTINE COMPLETED *****  CP =         0.469
*** ANSYS - ENGINEERING ANALYSIS SYSTEM  RELEASE 2022 R1 …
```
=> Command output repr

src/ansys/mapdl/core/plotting.py
I belie it does not make sense to plot when you are requesting the plotter as an output. Currently:
```py
>>> pl = mapdl.plot_nodal_displacements(return_plotter=True)  # This shows the plot
>>> pl.title = "New title"
>>> pl.show()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [4], in <module>
----> 1 p.show()
File c:\users\gayuso\other_projects\pyvista\pyvista\plotting\plotting.py:5027, in Plotter.show(self, title, window_size, interactive, auto_close, interactive_update, full_screen, screenshot, return_img, cpos, use_ipyvtk, jupyter_backend, return_viewer, return_cpos, **kwargs)
5024     raise DeprecationError(txt)
5026 if not hasattr(self, "ren_win"):
-> 5027     raise …
```
=> Not plotting if `return_plotter` is equal `True`.

.github/stale.yml
Adding a bot which notifies in stale issues, and eventually close them.
This bot has been added to the Pyansys org, but I only give rights to access pymapdl and pymapdl reader.
https://github.com/marketplace/stale
=> Adding stale bot.

src/ansys/mapdl/core/misc.py, tests/test_misc.py
Close #1062 by implementing ``AWP_ROOT{ver}`` env var.
=> Adding 'AWP_ROOT' var to get_ansys_bin

src/ansys/mapdl/core/mapdl_grpc.py, src/ansys/mapdl/core/pool.py
As the title.
I'm not removing ``tqdm`` from the toml file. But it should be possible. Since ``tqdm`` is not a very heavy package I would keep it, but since the functionality it provides is just sugar candy, I would. #FeedBackIsAppreciated
=> Making ``tqdm`` optional

src/ansys/mapdl/core/__init__.py, src/ansys/mapdl/core/_commands/preproc/elements.py, src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/misc.py, src/ansys/mapdl/core/plotting.py, tests/test_mapdl.py
Solves #1011 
Now, Pyvista and pyiges are lazy imported. 
Pyvista is made totally avoidable to install too. However, I did not remove pyvista from the toml file. But I'm open to discuss if we should or not.
=> Removing pyvista dependency

doc/source/api/mapdl.rst, src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/misc.py, tests/test_mapdl.py, tests/test_misc.py
This class provide some MAPDL information in a "dict-like" manner.
It is also the object that is called when you issue "print(mapdl)",
which means it is called by "mapdl.__str__()".
Notes
-----
You cannot directly modify the values of the keys.
The results are cached for later calls.
Examples
--------
```
>>> mapdl.info
Product:             Ansys Mechanical Enterprise
MAPDL Version:       21.2
ansys.mapdl Version: 0.62.dev0
>>> print(mapdl)
Product:             Ansys Mechanical Enterprise
MAPDL Version:       21.2
ansys.mapdl Version: 0.62.dev0
>>> mapdl.info['Product']
'Ansys Mechanical Enterprise'
>>> info = mapdl.info
>>> info['MAPDL Version']
'RELEASE  2021 R2           BUILD 21.2      UPDATE 20210601'
```
=> Mapdl.info property

src/ansys/mapdl/core/mapdl_grpc.py
this was failing:
```
mapdl.input('file.txt') # file.txt in os.getcwd()
```
Because we were passing to the /INPUT only the fname, not the full route. When the python working directory and MAPDL one are different, this will raise an error.
Now it should work.
=> `mapdl.input` not working in local and without fullpath

.github/workflows/label.yml
=> Fix labeler syntax

src/ansys/mapdl/core/misc.py, tests/test_misc.py
Instead of enforcing ``scooby``, I'm getting a basic template. I think this makes sense because of:
* Reduces the package dependencies (and package size)
* Most of the heavy lifting is done in ``mapdl_info``, which is still used; and when ``gpu`` is equal ``True`` which requires ``Pyvista``, which install ``scooby``. Since we do not want to depend on ``Pyvista``, I think this makes sense.
Close #1086
=> Removing ``scooby`` dependency

doc/source/conf.py, pyproject.toml, src/ansys/mapdl/core/launcher.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/test_launcher.py, tests/test_launcher_remote.py
This PR integrates [PyPIM](https://pypim.docs.pyansys.com/) in the `launch_mapdl` function. The intention is that a caller using `pymapdl.launch_mapdl()` without specific instructions on how to launch it will be redirected to using a remote instance when this is running in a pre-configured environment. This is the workflow targeted in the internal Ansys Lab.
This method will use PyPIM under the condition that:
- PyPIM is configured: See [pypim doc](https://pypim.docs.pyansys.com/api/index.html#ansys.platform.instancemanagement.connect)
- The user did not pass a specific executable path. In that situation, we assume that the caller have specific requirements
In this workflow, most of the configuration (arguments, ...) is ignored. While some of these configuration may be reintroduced later, …
=> PyPIM integration

src/ansys/mapdl/core/misc.py
I believe we should include PyMAPDL (``ansys.mapdl.core``) in the core packages of the ``Report`` class.
=> Adding missing package to report class

src/ansys/mapdl/core/parameters.py, tests/test_parameters.py
This PR does two things:
- Add a scape to ``interp_status`` for the edge case there is no parameters defined. Close #1107 
- Implement ``__contain__`` and ``__iter__`` methods. This way now we can do:
Because of the ``__contain__``:
```py
>>> mapdl.parameters['TWO'] = 2.0
>>> "TWO" in mapdl.parameters
True
>>> "THREE" in mapdl.parameters
False
```
Because of the ``__iter__``:
```
>>> for each in mapdl.parameters:
>>>     print(each)
"TWO"
```
Simple things, that I believe they will be useful.
=> Adding contain and iter methods.

pyproject.toml
This version doesn't contain any API breaking change or major feature, but starting from this version we will strictly follow semantic versioning.
This version dependencies will allow multiple PyAnsys libraries to depend on `~=1.something` while staying compatible together.
=> Bump PyPIM dependency version to ~=1.0

.github/dependabot.yml
Disable dependabot restriction on `ansys-mapdl-reader`
=> no longer need to pin ansys-mapdl-reader req

src/ansys/mapdl/core/mapdl.py, tests/test_mapdl.py
Added also unit tests.
Using ``=`` in ``mapdl.com`` was raising issues.
=> Fixing equal sign in comments and title.

src/ansys/mapdl/core/mapdl_grpc.py
Adding ``random_string()`` to make the input and output files non-fixed.
We should probably consider to use ``uuid.uuid4()`` but probably shorter. 
Close #1128
=> Using non-fixed input and output files

src/ansys/mapdl/core/mapdl_grpc.py
Progress bar in its current configuration operates in the opposite of the requested state. This PR fixes that.
=> disable download bar always on

src/ansys/mapdl/core/launcher.py
This PR makes pymapdl to be able to work without PIM package. However, it is still in the requirements. 
You should want to work without PIM when doing development.
Close #1150
=> Making PIM package lazy

src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_grpc.py
=> fix reset cache without pyvista

src/ansys/mapdl/core/mapdl_grpc.py
It seems the keyword arg `timeout` is not being passed through.
Close #1188
=> Timeout keyword argument not having effect

doc/source/api/helper.rst
As the title.
Adding 'convert_apdl_block' to docs.
Closes #1185
=> Adding 'convert_apdl_block' to docs

.github/workflows/ci.yml, pyproject.toml, requirements/requirements_tests.txt, src/ansys/mapdl/core/misc.py, tests/test_misc.py
=> Implement pyansys-tools-report in PyMAPDL

src/ansys/mapdl/core/licensing.py
We should just reuse the general logger created when the module is imported.
=> Using global logger in licensing

src/ansys/mapdl/core/launcher.py
Fix the mapdl ``clear_on_connect`` argument defaults when ``start_instance`` is used.
Close #1270
=> Fixing using ``clear_on_connect``

doc/source/examples/index.rst, src/ansys/mapdl/core/examples/downloads.py, tests/test_examples.py
Adding download section:
And also adding a helper:
```py
def _download_file(filename, directory=None):
url = _get_file_url(filename, directory)
try:
return _retrieve_file(url, filename)
except Exception as e:  # Genering exception
raise Exception(
"For the reason mentioned below, retrieving the file from internet failed.\n"
"You can download this file from:\n"
f"{url}\n"
"\n"
"The reported error message is:\n"
f"{str(e)}"
)
```
Close #1156
=> Download error page and helper

pyproject.toml
Last minor release, 0.62.0, was in 28 May. It's high time for a minor release.
Bump to v0.64.dev0 in preparation for a 0.63.0 release.
We'll keep this branch around for cherry-pick patch releases.
=> Bump to 0.64.dev0

src/ansys/mapdl/core/database/database.py, src/ansys/mapdl/core/errors.py, tests/test_database.py, tests/test_errors.py
=> Adding exception when starting database in a non-valid MAPDL version

.github/workflows/ci.yml, .github/workflows/nightly-doc-build.yml
Adding tag to documentation commits in documentation deployment repos.
Close #1171
=> Adding tags to documentation

doc/source/api/helper.rst, pyproject.toml, src/ansys/mapdl/core/__init__.py, src/ansys/mapdl/core/launcher.py
Add ``save_ansys_path`` to our docs and also expose it at the root module level. Seems like it should be both documented and more accessible.
=> add save_ansys_path to our docs

src/ansys/mapdl/core/launcher.py, src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_grpc.py, src/ansys/mapdl/core/pool.py, tests/test_launcher.py
Resolves #1314.
This PR modifies the behavior of ``remove_temp_files=True`` to only delete the MAPDL working directory when MAPDL is launched with ``run_location`` unset and the MAPDL current working directory remains as a sub-directory within the user temporary directory.
Ideally we'd track the files created by MAPDL and just delete those, but I don't have a way of getting an exhaustive list of files created by MAPDL. This seems to be a good compromise between cleaning unused files and not deleting user files should ``run_location`` be specified.
=> Delete the temporary working directory only in temp

.github/workflows/ci.yml, .github/workflows/nightly-doc-build.yml
Reverts pyansys/pymapdl#1282, seems to be failing:
```
remote: warning: See http://git.io/iEPt8g for more information.        
remote: warning: File PyMAPDL_documentation.zip is 57.69 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
To https://github.com/pyansys/pymapdl-docs.git
b24e07b..24a7cca  github-pages-deploy-action/mpcapw5fe -> gh-pages
Changes committed to the gh-pages branch… 📦
Adding 'v0.63.1' tag to the commit…
/usr/bin/git tag v0.63.1
fatal: tag 'v0.63.1' already exists
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/mpcapw5fe
Reset branch …
```
=> Revert "Adding tags to documentation"

src/ansys/mapdl/core/_commands/post26_/setup.py, src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/conftest.py, tests/test_mapdl.py
Resolve #1321 by addressing both the local and edge cases for the MAPDL ``FILE`` command.
Locally (at least on linux) running unit testing leaves behind 100s of processes of MADPL. Turns out that merely using `_kill` doesn't do the trick and you need to kill the MAPDL processes instead. Updated accordingly.
=> add remote and local cases for file

src/ansys/mapdl/core/math.py, tests/test_math.py
Complex ApdlMathObj using the copy method , Copies the real part and skips imaginary part.
Example :
Using Fz0 = Fz.copy()
Returns only the real part
=> Copy method updated to handle copying of complex ApdlMathObj

src/ansys/mapdl/core/post.py
=> Replace stray usage of `_get_array` with `get_array`

src/ansys/mapdl/core/_commands/session/files.py, src/ansys/mapdl/core/_commands/session/run_controls.py, src/ansys/mapdl/core/licensing.py, src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/test_licensing.py, tests/test_mapdl.py
Several tests are failing locally for a fresh install of MAPDL 2022R2 on Windows 10.
Fixes:
- Ensure MAPDL exits on Windows using `kill_server` rather than `_close_process`.
- Test normalized paths
- Do not test licensing unless license utility is available
- Fix `cwd` behavior to be multi-platform and raise rather than warn on a failed cwd change.
=> Fix windows tests

.github/labels.yml, .github/workflows/label.yml
This thing breaks way too much in my opinion.
But finally, it should close #1337.
=> Fixing labeler again

.ci/start_mapdl.sh, .github/workflows/ci.yml, .github/workflows/nightly-doc-build.yml, .github/workflows/nightly-mapdl-check.yml
Because many fails in #1343 I think we need better info about why the docker image is dying.
So I'm attempting to retrieve all the ``err``, ``out`` and ``log`` files. Also I have added the crash file.
=> Improving post mortem info

src/ansys/mapdl/core/__init__.py, src/ansys/mapdl/core/jupyter.py
So I did realize that VSCode was showing the wrong docstring info for ``launch_mapdl``, and it seems it is because of the import order.
=> Fixing order import

.github/workflows/ci.yml, README.rst, doc/source/getting_started/index.rst, src/ansys/mapdl/core/launcher.py
=> Fix/corba import, Python version docs, and Python 3.10 smoke tests

doc/source/user_guide/database.rst, doc/source/user_guide/index.rst, src/ansys/mapdl/core/database/__init__.py, src/ansys/mapdl/core/database/database.py, src/ansys/mapdl/core/database/elems.py, src/ansys/mapdl/core/database/nodes.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/test_database.py
Small improvements to database version checking and documentation.
Close #1325
=> Adding database notes and some improvements

.github/workflows/ci.yml
Most of the times the smoke tests do not fail. So delaying unit test by 3-4 minutes until the smoke tests are done seems to me a waste of time.
=> Removing needs from unit tests in CICD

codecov.yml, doc/source/getting_started/running_mapdl.rst, src/ansys/mapdl/core/launcher.py, src/ansys/mapdl/core/misc.py, tests/conftest.py
Currently, the Ansys Student installation overwrites the ``AWP_ROOT`` env var, hence it is chosen over a non-student version.
To simplify things and avoid the users to manually change the env var, I am forcing PyMAPDL to use (if available) non-student versions, even if they are an order version.
There is some nuances with this.
* Since the data is given in a dict, and dicts cannot have two equal keys, I'm using negative version for the student versions.
* I have also extended/updated the docs.
=> Prioritize the non-student versions

src/ansys/mapdl/core/mapdl_grpc.py, tests/test_grpc.py, tests/test_mapdl.py
Improving command error message by falling back to ``mapdl.run("*get, ...")`` in ``mapdl._get`` (grpc version of ``get``)
Close #1406
=> Improving error  message in ``mapdl.get_value``

.github/workflows/label.yml
It seems that dependabot has not enough permissions to run the commenter.
I'm going to try this... Wish me luck.
=> Fixing dependabot and commeter

.github/workflows/ci.yml, tests/test_files/full26.dat, tests/test_grpc.py
Sometimes the input tests fail mysteriously...
Updating tests and measuring times.
=> Improving input tests

src/ansys/mapdl/core/mapdl_grpc.py, tests/test_mapdl.py
As the title. Updated unit tests.
Close #1424
=> Adding ``write_to_log`` option to ``mapdl.input`` (grpc method)

src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/test_mapdl.py
Close #1451 by running ``mapdl.inquire("", "RSTFILE")`` and ``mapdl.inquire("", "RSTEXT")`` in the ``POST1`` processor.
=> Standardize the ``mapdl.inquire("", "RSTXXX")`` behaviour

src/ansys/mapdl/core/_commands/solution/load_step_options.py, src/ansys/mapdl/core/post.py, tests/test_post.py
Just adding ``frequency_values`` method.
=> Small harmonic analysis improvements

.ci/start_mapdl.sh, .github/workflows/nightly-doc-build.yml, .github/workflows/nightly-mapdl-check.yml, doc/source/getting_started/docker.rst
=> Expanding info about docker usage.

.github/workflows/nightly-doc-build.yml
As the title.
Current implementation was attempting to include the latex log file in the artifact, but the PDF is not built in the nightly.
=> Fixing doc build nightly.

examples/00-mapdl-examples/2d_plate_with_a_hole.py, examples/01-apdlmath-examples/solve_dense_matrix.py, examples/02-geometry/03-volumes.py, tests/conftest.py, tests/test_files/full26.dat
We don't need to take that much time.
Close #1407 
Close #1477
=> Reducing times for docs and testing

src/ansys/mapdl/core/launcher.py, src/ansys/mapdl/core/licensing.py, src/ansys/mapdl/core/logging.py, tests/test_launcher.py, tests/test_licensing.py
As the title. 
I also refactored the license checker class so now all the functions are methods.
=> Stopping license checker once it is connected 

src/ansys/mapdl/core/launcher.py
It seems that the VPN issue is fixed in the new Intel MPI 2021, hence we don't need to enforce MSMPI.
=> Removing VPN fix in latest MAPDL version

src/ansys/mapdl/core/launcher.py, tests/test_launcher.py
Removing verbose argument from license checker call.
=> Fix using license checker verbose argument internally

src/ansys/mapdl/core/_commands/apdl/macro_files.py, src/ansys/mapdl/core/mapdl.py, tests/test_mapdl.py
=> `mapdl.use` uploads macro file to remote instance

tests/conftest.py, tests/test_licensing.py
The docker image builiding was failing because of two things:
* Unsufficient time given to some license check threads
* The tests that requires license binaries were being executed although the testing was made in remote way.
I have added the `local` requirement to the license binaries tests, and also increased the waiting time before checking threads health.
Pinging @dts12263 for visibility
=> Fixing licensing in docker building cicd

.github/ISSUE_TEMPLATE/bug.yml
=> Improvements to template

.github/workflows/ci.yml
As the title.
This is because some modules (future `Krylov` module #1490 ) only runs on specific (last) MAPDL versions. Since I don't want coverage complains, I'm pushing this.
=> Upload a coverage report at every unit test job

src/ansys/mapdl/core/plotting.py, tests/test_plotting.py
Following a conversation with PyMAPDL-GUI team, this might be a requirement in the future.
Pinging @pvargasm @koubaa for visibility.
=> Adding plotter to inputs.

README.rst, doc/source/getting_started/docker.rst, doc/source/getting_started/index.rst, doc/source/getting_started/running_mapdl.rst, doc/source/getting_started/using_julia.rst, doc/source/getting_started/versioning.rst, doc/source/getting_started/wsl.rst, doc/source/index.rst, doc/source/learning/index.rst, doc/source/user_guide/convert.rst, doc/source/user_guide/database.rst, doc/source/user_guide/index.rst, doc/source/user_guide/launcher.rst, doc/source/user_guide/mapdl.rst, doc/source/user_guide/mapdl_examples.rst
I also fixed other Google style guide violations that I saw while skimming the file content. Most of these changes were removing future tense and double spaces between sentences. Content reviewed so far includes that in the Getting Started section and half of the User Guide section.
=> Change titles to sentence case

.gitignore, doc/source/examples/technology_showcase_examples/techdemo-20/20-example-technology-showcase-dynamic-simulation-PCB.py
Due to recent changes with parameters this example needs to be adjusted for the last section : 
mapdl.vget("frequencies(1)", 1)
mapdl.vget("response(1)", 3)
become:
mapdl.vget("frequencies", 1)
mapdl.vget("response", 3)
=> Correction of example for parameters extraction

doc/source/_static/custom.css, doc/source/_templates/sidebar-nav-bs.html, doc/source/conf.py, doc/source/examples/technology_showcase_examples/techdemo-28/ex_28-tecfricstir.rst
As proposed by @akaszynski 
Also added yellow role for text colouring.
=> Small improvements in sphinx build

doc/source/examples/extended_examples/Krylov/krylov_example.rst, doc/source/links.rst, doc/source/user_guide/krylov.rst
Here's the edited file. I'm going to leave a few comments/questions. Note that the existing Examples section needs to be reworked to following Google developer style guidelines. If you want to see better examples, look at those for PyAEDT. I also want to talk to German about breaking out the example sections in separate RST files so that the TOC for this section makes more sense.
=> General edit of Krylov example

.codespellrc, .pre-commit-config.yaml, doc/source/conf.py, doc/source/examples/technology_showcase_examples/techdemo-28/ex_28-tecfricstir.rst, examples/00-mapdl-examples/mapdl_beam.py, examples/04-general-fea/00-how_finite_element_works.py, src/ansys/mapdl/core/common_grpc.py, src/ansys/mapdl/core/database/nodes.py, src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/conftest.py
=> Update flake8 source import

examples/00-mapdl-examples/cyclic_static.py
Add a basic cyclic analysis example to the gallery.
It's super basic, and yes, I'm using the legacy result reader. @germa89, we can update this when DPF doesn't require 20 lines to plot a cyclic result.
=> add basic static cyclic example

doc/source/examples/index.rst
As title says. After merging #1649 we realized that there were some issues:
This PR will solve those issues
=> Solving rendering issues for examples documentation 

.github/workflows/ci.yml
As soon as you declare the `permissions` section, everything goes to null:
> If you specify the access for any of these scopes, all of those that are not specified are set to none.
We need write scope for the GH_TOKEN to write to the gh-pages branch.
=> FIX: gh_token scope

.github/workflows/ci.yml, .pre-commit-config.yaml, doc/Makefile, doc/make.bat, doc/source/conf.py, doc/validate_png.py, requirements/requirements_doc.txt
Adapt to multidoc for the last 3 releases. In favor of fix #1663
=> DOC: implement multi-doc in v0.61

.ci/start_mapdl_ubuntu.sh, .github/workflows/ci.yml
Because in https://github.com/pyansys/mapdl-docker-image-builder/pull/30 the root stopped to be the default user.
We need the root to operate at `/jobs`. Otherwise the CICD shows:
```text
Digest: sha256:3082a8d05bc4c0cd0e4a7e978be14c86f7cafd381ff0b556d097285a5db147a0
Status: Downloaded newer image for ghcr.io/pyansys/mapdl:v22.2-ubuntu
ghcr.io/pyansys/mapdl:v22.2-ubuntu
mkdir: cannot create directory '/jobs': Permission denied
Error: Process completed with exit code 1.
```
Also when using the docker image as a container for running the test locally we see the following error in the checkout action:
```text
Run actions/checkout@v3
/usr/bin/docker exec  76ecd63f3a8f7a867b0adef45933ee0e317478b8c8b47cf18b0a8dcbec98db83 sh -c "cat /etc/*release | grep ^ID"
##[debug]ID=ubuntu …
```
=> Adding root to docker run

.github/workflows/ci.yml, doc/source/links.rst, examples/00-mapdl-examples/exhaust_manifold_thermal_stress.py, examples/00-mapdl-examples/lathe_cutter.py, examples/00-mapdl-examples/transient_thermal.py, examples/02-geometry/01-lines.py, examples/02-geometry/02-areas.py, pyproject.toml, src/ansys/mapdl/core/mapdl_geometry.py, src/ansys/mapdl/core/math.py, src/ansys/mapdl/core/mesh_grpc.py, tests/test_math.py
Because of:
https://github.com/pyansys/pymapdl/actions/runs/3730672637/jobs/6327994564#step:13:73
I need to fix the numpy version to 1.23.5 until VTK fix:
https://github.com/Kitware/VTK/blob/726ca7c45bef7de71254d2377c810d23612a56da/Wrapping/Python/vtkmodules/util/numpy_support.py#L74-L88
=> Fixing numpy version

src/ansys/mapdl/core/convert.py
Simple fix to ensure we have platform independence when parsing filenames.
=> fix convert example

.github/workflows/dependabot.yml
The multiPR dependabot mood doesn't seem to have permissions to run workflows.
=> Fix dependabot permissions

src/ansys/mapdl/core/mapdl.py, tests/test_mapdl.py
To check if we are running on a docker container or not.
Added also ``is_local`` to expose ``mapdl._local``.
This is needed for #1300
=> Adding ``on_docker`` and ``is_local`` methods 

doc/source/getting_started/learning.rst, doc/source/getting_started/versioning.rst, doc/source/links.rst, src/ansys/mapdl/core/launcher.py
Remove setting ip in the grpc server (flaky).
Close #1503
=> Removing ip file option and small changes in learning section

doc/source/api/index.rst, doc/source/api/launcher.rst, doc/source/getting_started/contribution.rst, doc/source/getting_started/learning.rst, doc/source/getting_started/versioning.rst, src/ansys/mapdl/core/_version.py, src/ansys/mapdl/core/launcher.py, tests/test_launcher.py
Now you can use env vars to specify:
* Ansys executable path using ``PYMAPDL_MAPDL_EXEC``
* Ansys version using ``PYMAPDL_MAPDL_VERSION``
Additionally you can specify ansys version (if multiple are available) in ``launcher_mapdl(version=22.2)``.
Close #1566
=> Set Ansys version and executable from env vars

doc/source/conf.py, pyproject.toml
To improve user experience we are going to track the doc website usage, so we can see what parts of the website are more visited.
=> Adding google analytics tag

doc/source/api/mapdl.rst, doc/source/user_guide/mapdl.rst, src/ansys/mapdl/core/mapdl.py, tests/conftest.py, tests/test_mapdl.py
While working on https://github.com/pyansys/pymapdl/issues/1664
I saw that ``ignore_errors`` does nothing, in fact it is redundant with ``allow_ignore``. The later is more common, but I believe the naming is not the best.
So I am redirecting ``allow_ignore`` to ``ignore_errors`` and issuing a Deprecation warning when ``allow_ignore`` is used or set.
=> Deprecating ``allow_ignore`` in favor of ``ignore_errors``

doc/source/user_guide/troubleshoot.rst, src/ansys/mapdl/core/launcher.py, src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/parameters.py, tests/test_mapdl.py
This should avoid the command not being executed when you are in ``non_interactive`` or ``mapdl.input``.
It add the following argument ``avoid_non_interactive`` to each ``mapdl.run`` call.
I'm not documented this command because I believe its usage is going to be very restricted. But I'm conflicted about document it anyway
=> Adding ``avoid non interactive`` non-documented argument

src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_grpc.py
It should fix:
https://github.com/pyansys/pymapdl-examples/actions/runs/3938504282/jobs/6737289359#step:11:109
Let's enforce to use ``Mapdl.directory`` instead of ``Mapdl._path``.
=> Avoiding use 'self._path' in '_verify_local'

.github/workflows/ci.yml
Because of problems at the release problems. We are going back to this.
=> Coming back to old release procedures

tests/conftest.py
=> Skipping license check on launching MAPDL instance for test

src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/test_mapdl.py
Some functions such as ``load_array``, ``load_table``, ``input``, etc ... left some temporary files behind. This PR fixes that.
=> Removing temporary files at the end of execution

pyproject.toml
To do a release we need to remove all the direct (git based) dependencies.
The direct dependency was there because there was no release with the changes I proposed to this library in here: https://github.com/sphinx-contrib/googleanalytics/pull/7
=> Remove direct dependency

.github/workflows/ci.yml, pyproject.toml
As the title. 
Previously:
We amin to not attach the some of the pdfs but also attach the html documentation.
=> Clean artefact attached to Github release

src/ansys/mapdl/core/launcher.py, src/ansys/mapdl/core/pool.py
in function doc strings for `launch_mapdl` the examples were not pointing to the correct folder or exe.
while in the examples it is without `x`, which may lead to confusion
=> corrected doc string for example - on windows, folder is winx64

src/ansys/mapdl/core/mapdl.py, tests/test_mapdl.py
@dts12263 realised this tests is not properly done.
The line:
```py
if os.getenv("PYMAPDL_START_INSTANCE", "false") == "true":
```
was always evaluated ``False``
=> on_docker tests not correctly designed

pyproject.toml
Use the latest grpcio to better support Python 3.11 for doc builds.
=> Use grpcio==1.51.1 for docbuild

src/ansys/mapdl/core/parameters.py, tests/test_parameters.py
Close #1826 by making sure a correct parsing when string parameters contain spaces.
=> Fixing spaces in parameter string

src/ansys/mapdl/core/launcher.py, tests/test_corba.py, tests/test_launcher.py, tests/test_mapdl.py, tests/test_pool.py
Just fixing some tests
Close #1806
=> Fixing some tests

src/ansys/mapdl/core/mapdl_grpc.py
From #1749 
> When using the PyMAPDL input method I get an error when importing a CDB file when not specifying dir=....
Also clarifying the documentation.
Close #1749
=> Improving mapdl.input documentation

src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_grpc.py
This come from internal request:
> this is a follow-up on my last service request.
> We had issues with closing processes when using the SMP mode within a PyAnsys script.
> Your service member O.R. helped a lot and suggested to upgrade our python package with the following command.
> pip install --upgrade --upgrade-strategy eager ansys-mapdl-core The issue unfortunately still exists.
> DMP mode seem to work just fine with my crack growth (SMART) analysis.
I did try locally in ubuntu container, and on Windows 11; and it seems to work.
I will ask for internal feedback.
=Edit=
I have also added the module `atexit` to track exiting python using ``__del__`` method properly.
Close #1812
=> Recache processes to make sure we close them all.

src/ansys/mapdl/core/mapdl_grpc.py, tests/test_grpc.py
I am enforcing kwargs arguments on the gRPC methods (after ``*``)
Close #1833
=> Homogenization of input API

.github/workflows/ci.yml, src/ansys/mapdl/core/launcher.py, tests/test_launcher.py
Getting rid of the following message:
> /bin/sh: 1: gcc: not found
=> Removing gcc console output

pyproject.toml
After a discussion with @jorgepiloto, the way to fix it seems to impose `Sphinx==5.3.0` and `ansys-sphinx-theme==0.8.2`.
=> Modifying the Sphinx dependency version

src/ansys/mapdl/core/mapdl_grpc.py
=> Avoid checking non-existing process.

tests/test_mapdl.py, tests/test_parameters.py
These flags were implemented in #957 and they were probably phased out in #942. Although the dates doesn't add up, I guess the change (between XFAIL to XPASS) must be related to one of the mentioned PR.
Close #1844
=> Removing XPASS flag

src/ansys/mapdl/core/mapdl.py
The ``mapdl.aplot`` seems to give errors from time to time because it tries to allocate a huge array for area colouring. 
In this PR we limite the number of colours to be 256. The array size is still the same (number of areas), but now we use an ints instead of floats. 
Close #1691 and #1791
=> Limiting the number of scalars values for colour in aplot.

examples/00-mapdl-examples/3d_notch.py, src/ansys/mapdl/core/plotting.py
As the title. It allows us to get rid of `return_plotter` specification when using ``plotter``.
Close #1825
=> Passing plotter not requiring return_plotter

src/ansys/mapdl/core/math.py, tests/test_math.py
Code change to handle Issue  #1881  
Description of the Issue :
Indexing Items from a AnsVec of complex datatype which has both real and imag values, returns only the real value.
There is no way of accessing the imaginary value unless AnsVec is changed to numpy array.
Close #1881
=> Code update for Ansvec __getitem__ to handle complex dtype

src/ansys/mapdl/core/mapdl.py, tests/test_mapdl.py
Fix `Mapdl.use` to handle `name` specified as a kwarg.
=> Fix use name arg

src/ansys/mapdl/core/mapdl.py, tests/test_mapdl.py
Context environment to make sure we get output but not change state.
=> Implementing ``force_output``

src/ansys/mapdl/core/parameters.py, tests/test_mapdl.py
=> Raising warning if lenght of string is GT 32 chars

.github/workflows/label.yml
=> Fixing activation of labeler

src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/test_commands.py, tests/test_errors.py, tests/test_grpc.py, tests/test_inline_functions/test_query.py
As the title.
Use the same functions/methods for error handling.
This has been taken from #1912
=> Homogenising error handling

.github/workflows/ci.yml
I know this is not ideal.
Because of MAPDL being very unstable, having to run many times the unit tests, I'm going to allow to run each job in the test matrix independently of the others.
This way, we can save time/resources when MAPDL keeps crashing without reason.
Also I'm extending ``rerun`` policy to all the tests, independently of the exception raised.
=> Disabling fail-fast in the cicd

.github/workflows/ci.yml, src/ansys/mapdl/core/common_grpc.py
Discussed in #1919
Close #1919
=> Changing error in parse_chunks

src/ansys/mapdl/core/_commands/apdl/matrix_op.py, src/ansys/mapdl/core/math.py, tests/test_math.py
MAPDL V232 can perform Scaling (*SCAL) of a AnsMat / AnsVec by a vector. (New feature)
Introduce this feature in PyMAPDL Math Library by updating the existing inplace multiplication function __imul__.
This Feature is available only in MAPDL V232 and above.
=> Expose Vector Scaling introduced in MAPDL V232

.github/workflows/ci.yml
Reducing the amount of MAPDL versions where we do the testing.
I am trying to keep everything in the same YML, so this increases its complexity a bit but keep everything centralised.
=> Reducing MAPDL versions testing

src/ansys/mapdl/core/mesh/mesh.py, tests/conftest.py, tests/test_mapdl.py
As the title.
I'm not particularly happy of this implementation. It feels like a hack. I think the whole "save_as_vtk" needs to be fixed and improved server side.
Close #1948
=> Fixing plotting elements with midnodes

pyproject.toml, src/ansys/mapdl/core/mesh/mesh.py
PyVista v0.39.0 will be released by 1 May and will drop support for VTK v8. We have one minor change to make to be compatible with the to-be-released package.
=> Drop support for VTK v8

src/ansys/mapdl/core/misc.py, tests/test_misc.py
=> Return all the subtitles even if they are empty.

src/ansys/mapdl/core/launcher.py, src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/test_launcher.py
=> Raising error if using non allowed argument

src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/test_mapdl.py
Allowing to use ``input`` and ``input_strings`` inside ``non_interactive`` context manager.
Close #1246
=> Allowing to use ``input`` and ``input_strings``  inside ``non_interactive``

src/ansys/mapdl/core/parameters.py
I have been thinking a bit about this.
I personally believe this subclassing is the right way.
And although it is not need because most of the important methods, probably this subclassing can add something else we are missing now. So I would like to go ahead with this.
=> Adding more methods to ``Parameters``

src/ansys/mapdl/core/mapdl_grpc.py
=> Implementing ``checking_valid_IP`` on MapdlGrpc classs

src/ansys/mapdl/core/docs.py, src/ansys/mapdl/core/parameters.py, tests/test_mapdl.py, tests/test_parameters.py
As the title.
So we can do:
```py
mapdl.parameters["mypar"] = 1234
assert "mypar" in mapdl.parameters # True
assert "MYPAR" in mapdl.parameters # True also
```
=> Making contains method case insenstive

tests/test_database.py
As the title. Because CICD is not running on CentOS v22.2, this error wasn't caught.
=> Skipping test database test in v22.2

examples/01-apdlmath-examples/eigen_solve.py, examples/01-apdlmath-examples/scipy_sparse_matrix.py, examples/01-apdlmath-examples/solve_sparse_matrix.py, src/ansys/mapdl/core/misc.py
It seems that the old ``vm153.dat`` had the full file name embedded.
When the vms were updated in #2045, the command which changed the full file was deleted:
CICD should have catch this, but it reused the cached examples. I'm not sure how to solve that. I will open a different issue for that.
Close #2078
=> Fixing missing full file

src/ansys/mapdl/core/__init__.py, src/ansys/mapdl/core/launcher.py
Related to these relatively minor issues https://github.com/ansys/pyfluent/issues/1588, particularly the second one
`appdirs.user_data_dir("ansys_mapdl_core")` on Windows returns `%LocalAppData%\ansys_mapdl_core\ansys_mapdl_core`, which I don't think is what the original developer intended (note the repeated nested dir). On Linux it returns `~/.local/share/ansys_mapdl_core`. 
As in the appdirs documentation (https://github.com/ActiveState/appdirs/blob/master/appdirs.py#L44), if an `appauthor` is not specified, then by default on Windows it uses `appauthor=appname`. 
My suggestion is to use `user_data_dir(appname="ansys_mapdl_core", appauthor="Ansys")`, so that the path on Windows then is `%LocalAppData%\Ansys\ansys_mapdl_core` which is how apps more commonly do this on Windows in my …
=> Improving windows data path

tests/test_docs.py
As the title.
Those links were failing when doing a release because it was taking the branch as 'release/0.65'
=> Fixing linkcode tests for release

.github/workflows/dependabot.yml
=> Fix mutidependabot ci

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/examples.yml, .github/workflows/ci.yml, README.rst, doc/source/getting_started/index.rst, doc/source/user_guide/upf.rst, pyproject.toml, tox.ini
This would follow https://github.com/ansys/pyansys/pull/228.
=> Dropping Python 3.7 support

.github/workflows/dependabot.yml, pyproject.toml, src/ansys/mapdl/core/__init__.py, src/ansys/mapdl/core/misc.py
In February 2023 [appdirs has been deprecated](https://github.com/ActiveState/appdirs)
The developers suggest to move to [platformdirs](https://pypi.org/project/platformdirs/) which is a more active fork of appdirs
=> replace appdirs by platformdirs

.github/workflows/cache_cleaner.yml
Fix #2068.
Allows to delete all the cache using a workflow dispatch.
=> Fixing cache cleanup

pyproject.toml, src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/test_mapdl.py
=> Allowing savefig when vtk=false

src/ansys/mapdl/core/__init__.py, src/ansys/mapdl/core/mapdl_geometry.py
=> Fixing Pyvista for the next release

src/ansys/mapdl/core/_commands/database/components.py
=> Fixing non existing argument

pyproject.toml, src/ansys/mapdl/core/component.py, src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/mapdl_grpc.py, src/ansys/mapdl/core/plotting.py
=> Rolling back static python and scipy for python3.8 support

src/ansys/mapdl/core/_commands/preproc/material_data_tables.py
Also extending docstring.
Close #2185
=> Adding missing `mapdl.tbdele` argument

pyproject.toml, src/ansys/mapdl/core/pool.py
=> Adding timeout to pool.__getitem__ 

pyproject.toml
Bump `ansys-mapdl-reader` to 0.52.19
=> Bump `ansys-mapdl-reader` to 0.52.19

src/ansys/mapdl/core/__init__.py, tests/test_examples.py
Close #2191 
I will look into adding some unit tests, but it seems difficult to achieve.
```pycon
In [2]: import sys
In [3]: "ansys.mapdl.core" in sys.modules
Out[3]: False
In [4]: "requests" in sys.modules
Out[4]: False
In [5]: "ansys.mapdl.core.examples" in sys.modules
Out[5]: False
In [6]: from ansys.mapdl import core as pymapdl
In [7]: "ansys.mapdl.core" in sys.modules
Out[7]: True
In [8]: "ansys.mapdl.core.examples" in sys.modules
Out[8]: False
In [9]: "requests" in sys.modules
Out[9]: False
In [10]: from ansys.mapdl.core.examples import vmfiles
In [11]: "ansys.mapdl.core.examples" in sys.modules
Out[11]: True
In [12]: "requests" in sys.modules
Out[12]: True
```
=> Detaching `examples`

tests/test_launcher.py, tests/test_mapdl.py, tests/test_misc.py, tests/test_parameters.py, tests/test_plotting.py
The `pytest.mark.xfail` should be used when the implementation is not correct, or similar. So eventually, this will get fixed.
``XFAIL`` should not be used as a default when the test raises an exception because in that case, the implementation is behaving as expected and it should be a ``PASS``.
=> Removing xfails.

src/ansys/mapdl/core/inline_functions/core.py
=> Adding missing import in queries

.github/workflows/approver.yml
=> Small improvements to approver.

.github/labels.yml
It seems that github bot removes the reminder bot label. I hope adding this label to the labels file should fix it.
=> Fix reminder bot

.github/workflows/ci.yml
=> Using python 3.10 as default

.github/workflows/ci.yml, src/ansys/mapdl/core/__init__.py
=> Adding warnings for Python 3.8

.github/workflows/ci.yml
This step takes up to 4 minutes. It is too much time for the marginal usage we give it to it.
=> Removing listing files in build docs.

pyproject.toml
As the title. Because I removed it from #2248
=> Updating plotly.

src/ansys/mapdl/core/mapdl_grpc.py
=> Removing extension from file name, and using explicitly the ext field.

tests/conftest.py, tests/test_mapdl.py
Test that `ON_LOCAL` is running on distributed (`-DMP`).
Assumes that `ON_REMOTE` distributed should be `False` (because we specify `-SMP` when launching the docker image) and `ON_LOCAL` distributed should be `True` (because it is the default for MAPDL, and we dont specify `-SMP`).
To test if we are running distribute, we use the `*GET` command with `active` and `numcpu`:
https://github.com/ansys/pymapdl/blob/6916e19d2918fc476e299495b3a865f66e50918f/src/ansys/mapdl/core/parameters.py#L124-L125
I believe this is the right way.
=> Added distributed test

src/ansys/mapdl/core/plotting.py, src/ansys/mapdl/core/post.py
Fix the following issues:
* Empty `post_processing` plots #2288. Bug introduced in https://github.com/ansys/pymapdl/pull/2207
* Buggy colormaps plots #2296. It seems an issue with new PyVista API. It seems that passing `None` as cmap creates a buggy plot. We are avoiding this by setting a colormap (`bwr`) if no colormap is used.
PyMAPDL cmap does not work as cmap in `pyvista.Plotter.add_mesh`. We should fix that.
Close #2288 
Close #2296
=> Fixing `post_processing` plots

src/ansys/mapdl/core/mapdl.py
Improving SATIN command by implementing changes on #2285 
Close #2285 
Testing code:
```py
from ansys.mapdl.core import launch_mapdl
mapdl = launch_mapdl(log_apdl="log.log")
mapdl.satin(name="geom", extension="sat", fmt=0, entity="solid")
print(mapdl.geometry)
```
Using this file: https://github.com/ansys/pymapdl/discussions/2286#discussioncomment-6874620
=> Improving SATIN command

.github/workflows/cache_cleaner.yml, .github/workflows/ci.yml, .github/workflows/label.yml, .github/workflows/linkchecker.yml, .github/workflows/nightly-doc-build.yml, doc/source/examples/extended_examples/executable/executable.rst
As the title. Update checkout v3 to v4
=> Updating checkout action

.github/labels.yml, .github/workflows/ci.yml
As the title. 
Just to keep a better track of the issues in the nightly/scheduled.
=> Adding bot which open an issue if the scheduled build fails

src/ansys/mapdl/core/launcher.py
=> Document better the arguments "replace_env_vars" and "add_env_vars"

examples/00-mapdl-examples/geometry.py, examples/00-mapdl-examples/pressure_vessel.py, src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/misc.py
=> Fixing area meshing error in doc build

doc/source/examples/extended_examples/Krylov/krylov_example.rst
=> Small fixes in Krylov example

doc/source/user_guide/math.rst, examples/00-mapdl-examples/composite_dcb.py, examples/00-mapdl-examples/cyclic_static.py, src/ansys/mapdl/core/krylov.py, src/ansys/mapdl/core/xpl.py
As the title.
Routinary work checking PyMAPDL builds locally in windows.
Close #2255
=> Fix locally build docs in Windows

.github/workflows/ci.yml, .github/workflows/linkchecker.yml, tests/common.py, tests/conftest.py, tests/test_importing_geometries.py
=> Fix geometry connection command tests on earlier MAPDL versions

.github/workflows/ci.yml, examples/00-mapdl-examples/3d_notch.py, examples/00-mapdl-examples/modal_beam.py
Thanks to @mcMunich for suggesting it
Close #2310
=> Add modal example

src/ansys/mapdl/core/mapdl.py, src/ansys/mapdl/core/misc.py, src/ansys/mapdl/core/plotting.py, tests/test_plotting.py
=> Adding lines to `kplot` and `nplot` when using mouse picking

.github/workflows/ci.yml, doc/source/conf.py
This pull-request enables PyMeilisearch. This tool enhances the user experience when using the search bar.
In https://github.com/ansys/pyfluent/commit/fdf78e4590f9fedaddd32e3bfe165b45243f5d5c the option is enabled in the HTML theme configuration.
Later, in https://github.com/ansys/pymapdl/pull/2368/commits/a754f43ec229dba26cb1ac3dabdfe44c5622ae73 and https://github.com/ansys/pymapdl/pull/2368/commits/b7dc66c910eb127a1188f2576c45b18f72867dcf, the documentation gets indexed.
=>  doc: enhance search bar experience by using pymeilisearch

.github/workflows/ci.yml
=> Activate database testing in local. It should be skipped by pytest db fixture.

pyproject.toml
The search engine is not running correctly on the stable branch. This should fix the issue. 
Pinging @Revathyvenugopal162 for visibility.
Close #2404
=> maint: updating `ansys-sphinx-theme` version

src/ansys/mapdl/core/mapdl.py
=> Fix `mapdl.get` always asking for multiline output when using `item3`

codecov.yml
It is quite annoying to see a failed job because a slow job hasn't yet submitted its coverage report yet.
=> Delaying codecov report until CI is finished

.github/workflows/ci.yml
It seems that CICD is failing, not being able to run succesfully even a single test.
Fixed. See https://github.com/ansys/pymapdl/pull/2514#issuecomment-1818993728
=> Fixing CICD: Adding missing `libgomp1` dependency

src/ansys/mapdl/core/launcher.py, tests/test_launcher.py
=> Allowing latest as version

.github/workflows/ci.yml
* Adding permissions for writing issues. 
* Formatting
Close #2559
=> Fixing issue opener for scheduled jobs

.github/workflows/approver.yml
* Improving autoapprover so it does not run unless some user/comment is fulfilled. Moving the 'if' logic to the job level, instead of the step level.
=> Not running auto approver by default

doc/source/user_guide/mapdl.rst, doc/source/user_guide/post.rst
As the title.
Minor cosmetic changes.
Close #2538
=> Reworking post-processing section

.github/workflows/label.yml
As the title.
I believe passing the token should fix it.
=> Fixing set_labels

.devcontainer/codespaces-docs/welcome.rst, src/ansys/mapdl/core/errors.py, src/ansys/mapdl/core/launcher.py, tests/test_launcher.py
=> Checking number of processors before launching.

src/ansys/mapdl/core/launcher.py, tests/test_mapdl.py
One test (``test_check_stds``) was raising the following exception:
```text
E           ansys.mapdl.core.errors.MapdlConnectionError: [libprotobuf ERROR /home/staff/kkripa/tfsagent/_work/20/b/.conan/data/protobuf/3.10.1.3/thirdparty/stable/build/2a45a8e4e8f3a96579715eed8e14250652eeb4d4/protobuf/src/google/protobuf/wire_format_lite.cc:578] String field 'ansys.api.mapdl.v0.CmdResponse.response' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
E           Attempting to use an MPI routine after finalizing MPICH
```
However I'm quite sure it wasn't because of this test. Very likely it was in a previous tests, and it was just caught here.
This error only affected the ubuntu MAPDL v23.2 image.
I might check later (on day) what …
=> Fixing MPI message

src/ansys/mapdl/core/common_grpc.py, src/ansys/mapdl/core/errors.py, tests/test_errors.py
I'm not very convinced on this one...
The idea is to have all the MAPDL error classes deriving from one (``MapdlException``), so we can do something like:
```py
try:
mapdl = launch_mapdl()
except MapdlException:
handle_pymapdl_exception()
except Exception:
```
With the current implementation, you can do this too:
```py
try:
raise MapdlValueError
except MapdlValueError:
handle_value_error()
except MapdlException:
handle_value_error()
except MapdlException:
handle_value_error()
except Exception:
handle_value_error()
```
I think it could add value, but it does generate maybe complicated inheritance relationships:
```mermaid
graph TD;
Exception-->ValueError;
Exception-->MapdlException;
ValueError-->MapdlValueError;
MapdlException--> MapdlValueError;
```
Because ``MapdlValueError`` inheritates …
=> Deriving all custom error from Exception and related

.github/workflows/approver.yml
Because it was using the default token, it was the github actions bot who was reacting.
=> Changing token in approval reaction

src/ansys/mapdl/core/logging.py
=> Disabling catching all in logger

doc/source/getting_started/write_documentation.rst, doc/source/links.rst, examples/02-tips-n-tricks/00-example-template.py
Improving example template and documentation.
Close #2370
=> Improving example template

src/ansys/mapdl/core/mapdl_core.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/test_mapdl.py
This check penalise the performant quite a lot since several gRPC calls are made.
I'm disabling it for the moment.
Ideally we will have to implement something on the server side.
Close #2608
=> Disabling session ID check by default

src/ansys/mapdl/core/mapdl_grpc.py, tests/test_mapdl.py
As the title.
Here we are implementing approach ``a`` in https://github.com/ansys/pymapdl/issues/2772#issuecomment-1941613370.
Close #2772
=> Fix get_value

src/ansys/mapdl/core/mapdl_core.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/test_mapdl.py
To show/download screenshots.
```py
mapdl.screenshot()
```
Close #2845 
<details><summary>Details</summary>
<p>
```py
import numpy as np
from ansys.mapdl.core import launch_mapdl
mapdl = launch_mapdl(loglevel="WARNING", print_com=True)
mapdl.com("ANSYS MEDIA REL. 2023R2 (05/12/2023) REF. VERIF. MANUAL: REL. 2023R2")
mapdl.prep7()
mapdl.title("VM151, NONAXISYMMETRIC VIBRATION OF A CIRCULAR PLATE")
mapdl.com("FORMULAS FOR NATURAL FREQUENCY AND MODE SHAPE, BLEVINS, PAGE 240")
mapdl.et(1, "SHELL61")
mapdl.r(1, .05)  # THICKNESS OF PLATE
mapdl.mp("EX", 1, 30E6)
mapdl.mp("DENS", 1, .00073)
mapdl.mp("PRXY", 1, 0.3)
mapdl.k(1)
mapdl.k(2, 3)
mapdl.l(1, 2)
mapdl.lesize(1, "", "", 9)
mapdl.lmesh(1)
mapdl.nsel("S", "LOC", "X", 0)
mapdl.d("ALL", "UX")
mapdl.nsel("S", "LOC", "X", 3)  # SELECT NODE AT …
```
=> Adding screenshot method.

doc/source/getting_started/install_pymapdl.rst, doc/source/user_guide/cli.rst, doc/source/user_guide/upf.rst, doc/styles/Vocab/ANSYS/accept.txt
=> Fix documentation

src/ansys/mapdl/core/launcher.py, src/ansys/mapdl/core/misc.py, tests/test_launcher.py, tests/test_misc.py
=> Removing redundancies

tests/test_xpl.py
=> Skipping `test_xpl.py::test_save` on v24.2

doc/source/api/pool.rst, doc/source/user_guide/pool.rst, src/ansys/mapdl/core/__init__.py, src/ansys/mapdl/core/pool.py, tests/test_pool.py
As the title.
This is a leftover of #2862
=> Renaming LocalMapdlPool class

.github/workflows/linkchecker.yml, doc/source/conf.py
=> Fix linkchecker workflow

src/ansys/mapdl/core/launcher.py, tests/test_launcher.py
As the title.
Adding tests
Related to https://github.com/ansys/pymapdl/issues/2910
=> Avoiding having both "start_instance" and "ip" set.

src/ansys/mapdl/core/launcher.py, tests/test_launcher.py
As the title.
To be merged to main after https://github.com/ansys/pymapdl/pull/2912
=> Adding a warning if there is a conflict between env vars and arguments

src/ansys/mapdl/core/cli.py, tests/test_cli.py
=> Ignoring `PYMAPDL_START_INSTANCE` env var on CLI `pymapdl start`

tests/common.py, tests/conftest.py
As the title.
It am added some printing related to env vars:
```output
------------------------------------------------------------Testing variables-------------------------------------------------------------
Session dependent: ON_CI (False), TESTING_MINIMAL (False), SUPPORT_PLOTTING (True)
OS dependent: ON_LINUX (False), ON_UBUNTU (False), ON_WINDOWS (False), ON_MACOS )(True)
MAPDL dependent: ON_LOCAL (False), ON_STUDENT (False), HAS_GRPC (True), HAS_DPF (True), IS_SMP (True)
----------------------------------------------------------Environment variables-----------------------------------------------------------
PYMAPDL_START_INSTANCE ('False'), PYMAPDL_PORT ('50092'), PYMAPDL_DB_PORT ('50095'), DPF_PORT ('50056'), DPF_START_SERVER ('false'), …
```
=> Adding a more comprehensive printing in pytest

src/ansys/mapdl/core/launcher.py
As the title.
The issue was an infinite loop while launching MAPDL.
Once I added:
```py
from ansys.mapdl.core import LOG
LOG.setLevel("DEBUG")
LOG.log_to_file("mylog.log")
```
to the first example, I was able to get:
```text
DEBUG - pymapdl_global -  launcher - launch_mapdl - Using default port 50052
DEBUG - pymapdl_global -  launcher - launch_mapdl - Building gallery.
DEBUG - pymapdl_global -  launcher - get_start_instance - PYMAPDL_START_INSTANCE is unset. Using default value True.  
DEBUG - pymapdl_global -  launcher - launch_mapdl - Using 'start_instance' equal to True.
DEBUG - pymapdl_global -  launcher - launch_mapdl - No IP address was supplied. Using the default IP address: 127.0.0.1
DEBUG - pymapdl_global -  launcher - launch_mapdl - Using default port 50052
DEBUG - …
```
=> Fix doc builds in Windows

.ci/collect_mapdl_logs.sh, .ci/start_mapdl.sh, .github/workflows/ci.yml, src/ansys/mapdl/core/_version.py, src/ansys/mapdl/core/database/database.py, tests/test_database.py
=> Adding v242 to CICD

src/ansys/mapdl/core/parameters.py
As the title.
Simple change but it seems effective.
Instead of printing the array using floating numbers (``F``) we use exponential (``E``).
```console
((.venv_py312) ) ➜  pymapdl git:(feat/more-precision-retrieving-arrays) ✗ python tmp/main.py
[ 0.000e+00  0.000e+00 -4.580e-10 -8.780e-10 -2.180e-10 -2.680e-10
-3.790e-10 -5.410e-10 -4.700e-10 -8.150e-10  4.580e-10 -8.780e-10
0.000e+00 -1.473e-09  0.000e+00  0.000e+00  4.700e-10 -8.150e-10
3.790e-10 -5.410e-10  2.180e-10 -2.680e-10  0.000e+00  0.000e+00
0.000e+00 -1.910e-10  0.000e+00 -4.900e-10  0.000e+00 -8.640e-10]
-4.58e-10
```
```console
((.venv_py312) ) ➜  pymapdl git:(feat/more-precision-retrieving-arrays) ✗ python tmp/main.py
[ 0.00000000e+00  0.00000000e+00 -4.58300835e-10 -8.78066913e-10
-2.18264131e-10 -2.68102076e-10 …
```
=> Improving precision in array retrieval

src/ansys/mapdl/core/_commands/apdl/abbreviations.py, src/ansys/mapdl/core/_commands/apdl/array_param.py, src/ansys/mapdl/core/_commands/aux12_/radiation_mat.py, src/ansys/mapdl/core/_commands/aux12_/radiosity_solver.py, src/ansys/mapdl/core/_commands/aux15_.py, src/ansys/mapdl/core/_commands/aux2_/bin_dump.py, src/ansys/mapdl/core/_commands/aux2_/bin_manip.py, src/ansys/mapdl/core/_commands/aux3_.py, src/ansys/mapdl/core/_commands/conn.py, src/ansys/mapdl/core/_commands/database/components.py, src/ansys/mapdl/core/_commands/database/coord_sys.py, src/ansys/mapdl/core/_commands/database/picking.py, src/ansys/mapdl/core/_commands/database/selecting.py, src/ansys/mapdl/core/_commands/database/setup.py, src/ansys/mapdl/core/_commands/database/working_plane.py, src/ansys/mapdl/core/_commands/display_/setup.py, src/ansys/mapdl/core/_commands/graphics_/annotation.py, src/ansys/mapdl/core/_commands/graphics_/graphs.py, src/ansys/mapdl/core/_commands/graphics_/labeling.py, src/ansys/mapdl/core/_commands/graphics_/scaling.py, src/ansys/mapdl/core/_commands/hidden.py, src/ansys/mapdl/core/_commands/map_cmd.py, src/ansys/mapdl/core/_commands/post1_/load_case.py, src/ansys/mapdl/core/_commands/preproc/database.py
=> Some format fix in docstrings

.github/ISSUE_TEMPLATE/bug.yml
Knowing the MAPDL version used to obtain the bug can usually help.
For now, it can be accessible with the `PyMAPDL report` section but I think it would be more visible this way. Also, one can have multiple MAPDL versions installed.
=> feat: add a `MAPDL version` section in for bug issues

src/ansys/mapdl/core/mapdl_grpc.py, tests/test_mapdl.py
*This is a development only command, not intended for general use*
The option1 was missing in the function definition.
=> Adding option to `_ctrl` command

doc/source/conf.py
=> Customize agent for linkchecker

doc/source/mapdl_commands/prep7/special_purpose.rst, src/ansys/mapdl/core/_commands/preproc/special_purpose.py
Adding ``cycexpand`` command. 
Close #3020
=> Adding cycexpand

doc/source/user_guide/pool.rst, src/ansys/mapdl/core/pool.py, tests/test_pool.py
=> Adding context manager to MapdlPool

doc/source/user_guide/pool.rst, src/ansys/mapdl/core/pool.py
As the title.
Now if we are providing a list of ports, the number of instances argument (``n_instances``) is optional, not needed.
=> Adding documentation about remote mapdl pool

tests/test_xpl.py
This reverts commit ea42836ed7c3d3141f43dc78b114da17bf7a033e.
The bug should have been fixed by now.
=> Revert "Skipping `test_xpl.py::test_save` on v24.2 (#2905)"

src/ansys/mapdl/core/cli/hpc.py, src/ansys/mapdl/core/hpc/pyhps.py
=> Adding inputs and outputs

src/ansys/mapdl/core/cli/__init__.py
This function should have given an error when using if click was not installed.
=> Making old API function discoverable when Click is not installed.

.github/CODEOWNERS, .pre-commit-config.yaml, AUTHORS, CODEOWNERS, CONTRIBUTORS.md, README.md, pyproject.toml
- update `pyproject.toml` file
- update `authors` file
- update `codeowners` files
- Add `contributors` file
=> fix: update the general files to align with PyAnsys standards

src/ansys/mapdl/core/convert.py, tests/test_convert.py
=> Converting chained APDL commands to PyMAPDL context manager.

.github/workflows/ci.yml, doc/changelog.d/3171.miscellaneous.md
Following PyAnsys guidelines, this PR is to implement the [ansys/actions/release-pypi-public](https://actions.docs.ansys.com/version/6.1/migrations/release-pypi-trusted-publisher.html#release-pypi-trusted-publisher).
=> ci: using trusted publisher release process

doc/changelog.d/3166.miscellaneous.md, src/ansys/mapdl/core/pool.py, tests/test_pool.py
As the title.
It should allow to:
```py
ips = [
"123.45.67.01",
"123.45.67.02",
"123.45.67.03",
"123.45.67.04",
"123.45.67.05",
]
pool = MapdlPool(ip=ips)
```
=> feat: allowing multiple IPs for remote connection on `MapdlPool`

.github/workflows/ci.yml, doc/changelog.d/3186.changed.md
To avoid running CICD on testing tags. Close #3185
=> ci: Use CICD only on ``v*`` tags.

doc/changelog.d/3198.added.md, pyproject.toml, src/ansys/mapdl/core/mapdl_inprocess.py
This PR add a new backend that will be used by MAPDL when exposing a python interpreter with PyMapdl.
It takes a module containing the function `run_command` as an argument.
=> feat: Add an inprocess backend to pymapdl

.github/workflows/ci.yml, doc/changelog.d/3225.fixed.md
The CICD was uploading all the remote testing as CentOS.
Close #3190
=> ci: wrong tagging on the coverage artifacts

.github/workflows/ci.yml, doc/changelog.d/3223.changed.md
The unit tests are not running currently because of the last reorg of the workflow steps done in https://github.com/ansys/pymapdl/pull/3171, because now they depends on the smoke tests which were not running previously on schedule or workflow dispatch.
NA
=> ci: improving if to match also schedule and workflow_dispatch

.github/workflows/ci.yml, doc/changelog.d/3237.changed.md
Increase the files checked for changes before load docs cache.
Currently CICD does not check changes in the `doc` directory. This checks against it.
NA
=> ci: increase the files checked for changes before load docs cache

.ci/build_matrix.sh, .github/workflows/ci.yml, doc/changelog.d/3251.fixed.md, tests/conftest.py
Because of ``ON_STUDENT`` env var, all the local and minimal tests were running as student. So some pool and CLI tests were not running.
Close #3250
=> fix: local tests always running as student

.devcontainer/codespaces-docs/requirements.txt, doc/changelog.d/3224.dependencies.md, doc/source/conf.py, pyproject.toml
This is extension is no longer used (or at least I couldn't make it work properly ... almost ever). 
Furthermore, with the change in the domain at the higher level, I dont think this extension is explicable for the current cases.
Close #3216
=> build: removing reredirect sphinx extension

doc/changelog.d/3255.dependencies.md, doc/source/examples/extended_examples/hpc/requirements.txt, minimum_requirements.txt, pyproject.toml
Update ``ansys-api-mapdl`` to 0.5.2.
NA
=> build: update ansys-api-mapdl to 0.5.2

doc/changelog.d/3259.added.md, tests/test_cli.py, tests/test_mapdl.py
Recent changes on testing, make that some tests which where not tested before, are now tested.
The issue is a bit complex, because PyMAPDL leave some MAPDL instances loose, so I should make sure that ``mapdl.exit`` works properly.
Because other developers downstream needs ``ansys-api-mapdl`` 0.5.2, I'm going to do a patch release skipping these tests.
Related to #3254, #3257
=> test: skip test

doc/changelog.d/3263.fixed.md, src/ansys/mapdl/core/cli/list_instances.py
=> fix: not showing instances on linux

.github/workflows/ci.yml, doc/source/user_guide/pool.rst, tests/test_pool.py
Increase timeout in local-min
Close #3286
=> fix: local-min timeout

doc/changelog.d/3295.fixed.md, src/ansys/mapdl/core/_commands/preproc/sections.py
Fix missing arguments in SECDATA.
Close #3278
=> fix: missing arguments in secdata

doc/changelog.d/3315.fixed.md, tests/conftest.py, tests/test_pool.py
Some pool tests weren't properly skip.
NA
=> fix: Making sure we skip all the pool unit tests.

doc/changelog.d/3328.dependencies.md, pyproject.toml, src/ansys/mapdl/core/launcher.py, src/ansys/mapdl/core/mapdl_core.py, tests/common.py, tests/conftest.py
=> feat: adding `PYMAPDL_APDL_LOG` env var for testing

doc/changelog.d/3362.miscellaneous.md, tests/conftest.py
fixing newly added mapdl.tbdat to mapdl.tbdata to fix the following
[ERROR] TestFieldComponentValueGetter.test_temp - E           AttributeError: 'MapdlGrpc' object has no attribute 'tbdat'
[ERROR] TestFieldComponentValueGetter.test_pressure - E           AttributeError: 'MapdlGrpc' object has no attribute 'tbdat'
[ERROR] TestFieldComponentValueGetter.test_volt - E           AttributeError: 'MapdlGrpc' object has no attribute 'tbdat'
[ERROR] TestFieldComponentValueGetter.test_mag - E           AttributeError: 'MapdlGrpc' object has no attribute 'tbdat'
**Please provide a brief description of the changes made in this pull request.**
=> Update conftest.py to switch mapdl.tbdat to mapdl.tbdata

.github/workflows/ci.yml, doc/changelog.d/3326.added.md, pyproject.toml, src/ansys/mapdl/core/__init__.py
Dropping python3.9 official support. 
Using python3.11 for official testing.
~~However, I am going to keep one outdated version (python3.9) as part of the CICD, just testing installation and imports.~~ Nevermind, to do this I need to install the library with ``--ignore-requires-python`` argument but since we are using an ``ansys/action`` probably it is not worthy to remove completely the action just for this smoke test.
NA
=> chore: drop python3.9 support

doc/changelog.d/3355.fixed.md, pyproject.toml, src/ansys/mapdl/core/mapdl_grpc.py
Check if input is called from `CDREAD`, if it is, it does not upload the file again.
Close #3348
=> fix: reuploading file on CDREAD

doc/changelog.d/3384.added.md, tests/test_database.py
Deactivate database tests on v23.X.
NA
=> chore: skip database testing on v23.X

doc/changelog.d/3396.documentation.md, doc/source/index.rst
keywords in the metadata should be `comma` seperated, https://docutils.sourceforge.io/docs/ref/rst/directives.html#meta
otherwise, all the keywords treated as single word by seo and give [result ](https://www.google.com/search?q=pymapdl+mapdl+simulation+finite+elements+python&rlz=1C1GCEA_enFR1004FR1004&oq=py&gs_lcrp=EgZjaHJvbWUqBggAEEUYOzIGCAAQRRg7MgYIARBFGEAyBggCEEUYOTINCAMQABiDARixAxiABDIGCAQQRRg7MgYIBRBFGDwyBggGEEUYPDIGCAcQRRg80gEIMTU3MGowajeoAgCwAgA&sourceid=chrome&ie=UTF-8)
no issue created
=> docs: fix keywords metadata

doc/changelog.d/3412.miscellaneous.md, src/ansys/mapdl/core/commands.py, tests/test_commands.py
to_dataframe() support for the output of following list boundary conditions commands: DKLIST, DLLIST, DALIST,  FKLIST, SFLLIST, BFKLIST, BFLLIST and BFALIST
N / A
=> feat: supporting ´´to_dataframe()´´ for some bc list commands

doc/changelog.d/3414.documentation.md, doc/source/index.rst
change the cards layout for the landing page
_
=> docs: cards layout for the landing page

doc/changelog.d/3428.fixed.md, src/ansys/mapdl/core/mapdl_core.py
Avoid writing to close IO strem when logging using `__del__` method.
NA
=> fix: disabling logging on `__del__`

doc/changelog.d/3435.miscellaneous.md, src/ansys/mapdl/core/mapdl_inprocess.py
This will be implemented by the backend, after which the `hasattr` check can be removed here.
=> feat: add exit to inprocess backend

.pre-commit-config.yaml, doc/changelog.d/3445.maintenance.md
Using commits and PR names according to repo standards.
NA
=> ci: changing pre-commit commit and pr name

doc/changelog.d/3460.miscellaneous.md, src/ansys/mapdl/core/__init__.py, src/ansys/mapdl/core/mapdl_core.py, src/ansys/mapdl/core/mapdl_extended.py, src/ansys/mapdl/core/misc.py, src/ansys/mapdl/core/plotting/__init__.py, src/ansys/mapdl/core/plotting/visualizer.py, src/ansys/mapdl/core/post.py
Fix an issue where having pyvista but not the visualizer will break the imports.
Now we have two flags.
- `_HAS_PYVISTA` which is used for non-plotting capabilities, like `mapdl.geometry` and `mapdl.mesh` modules.
- `_HAS_VISUALIZER` for plotting capabilities like `mapdl.nplot` and `mapdl.post` module.
The visualizer requires pyvista, so it is more strict flag than the pyvista only.
This PR acknowledges that `pyvista` is used in more places than just for plotting. Hence PyMAPDL is not totally decoupled from `pyvista`.
If we want to use all the features, for instance `mapdl.mesh` and `mapdl.geometry`, we need `pyvista`.
NA
=> feat: having two global flags. One for visualizer and one for pyvista

doc/changelog.d/3461.fixed.md, src/ansys/mapdl/core/launcher.py, tests/test_launcher.py
Explicitly using the current environment  (`os.environ.copy`) in the MAPDL process. This should fix some issues reported internally where MAPDL couldn't start because some env vars weren't being passed.
NA
=> fix: environment variables not being passed to MAPDL process

.github/workflows/ci.yml, doc/changelog.d/3472.maintenance.md
With the new `ansys/actions` v8 (see #3470) I realised that dependabot cannot trigger the matrices because it is not part of any team, so that part of the action fails.
Related to #3470
=> ci: bypass team check if it is dependabot

doc/changelog.d/3487.miscellaneous.md, src/ansys/mapdl/core/launcher.py, tests/test_launcher.py
Until now `PYMAPDL_NPROC` was only accepted when running on SLURM. With this PR, we also accept that env var for setting the number of cores in a normal run (no SLURM).
=> feat: adding 'pymapdl_nproc' to non-slurm runs

.github/workflows/ci.yml, doc/changelog.d/3505.maintenance.md, src/ansys/mapdl/core/launcher.py, src/ansys/mapdl/core/licensing.py, src/ansys/mapdl/core/mapdl_core.py, src/ansys/mapdl/core/mapdl_grpc.py
This PR enables the ``ansys/actions/check-vulnerabilities`` to CI-CD.
=> ci: ``ansys/actions/check-vulnerabilities`` to CI-CD

doc/changelog.d/3507.fixed.md, src/ansys/mapdl/core/launcher.py
The following 
```py
from ansys.mapdl.core import launch_mapdl
mapdl = launch_mapdl(start_instance=False, port=50053)
```
was giving the error ``PortInUse``.
=> fix: raising port busy when connecting

doc/changelog.d/3523.added.md, tests/conftest.py, tests/test_post.py
Moving the tests to classes to speed up testing.
```
Time (mean ± σ):     42.118 s ±  5.528 s    [User: 8.025 s, System: 3.524 s]
Range (min … max):   35.268 s … 53.661 s    10 runs
```
``` 
Time (mean ± σ):     28.822 s ±  7.450 s    [User: 6.949 s, System: 3.077 s]
Range (min … max):   22.796 s … 43.364 s    10 runs
```
NA
=> refactor: moving tests to classes to avoid repeated fixtures execution

doc/changelog.d/3528.miscellaneous.md, src/ansys/mapdl/core/launcher.py, tests/test_launcher.py
=> feat: using version instead of exec_path for the MPI checks

doc/changelog.d/3540.fixed.md, src/ansys/mapdl/core/cli/list_instances.py
=> fix: checking port on non-grpc mapdl instances

.github/dependabot.yml, doc/changelog.d/3546.documentation.md, doc/source/examples/extended_examples/hpc/requirements.txt, minimum_requirements.txt, pyproject.toml, src/ansys/mapdl/core/report.py
It should not be required anymore in the version range that we support (importlib.metadata is builtin now)
=> maint: remove importlib-metadata requirement

codecov.yml, doc/changelog.d/3542.added.md
While checking stuff in `PyAEDT` codecov result (use of multiple tags) I wanted to double check what was done in other repos. When checking the latest main's commit codecov I saw a warning, see below
This PR consists in fixing the "bug" that is reported by codecov.
To double check you can use the following command from the root of your repo
`curl -X POST --data-binary @codecov.yml https://codecov.io/validate`
Before the changes there is an error associated to "comment", now it's no longer present :)
=> chore: fix codecov.yml content

doc/changelog.d/3551.added.md, src/ansys/mapdl/core/mapdl_core.py, src/ansys/mapdl/core/mapdl_geometry.py, src/ansys/mapdl/core/mapdl_grpc.py, src/ansys/mapdl/core/misc.py, tests/test_misc.py
=> refactor: removing-`run_as_prep7`-in-favour-of-`run_as`

.ci/build_matrix.sh, doc/changelog.d/3564.maintenance.md
As the title. To reduce workload.
NA.
=> ci: skipping student versions when user is authenticated

doc/changelog.d/3560.added.md, doc/source/api/launcher.rst, doc/source/getting_started/launcher.rst, src/ansys/mapdl/core/__init__.py, src/ansys/mapdl/core/launcher.py, tests/conftest.py, tests/test_launcher.py, tests/test_pool.py
As the title. Because `find_ansys` is going to be deprecated.
NA
=> refactor: using find_mapdl instead of find_ansys

doc/changelog.d/3556.added.md, src/ansys/mapdl/core/post.py, tests/test_post.py
=> refactor: increase post module coverage

doc/changelog.d/3570.fixed.md, src/ansys/mapdl/core/__init__.py, src/ansys/mapdl/core/helpers.py, tests/test_mapdl.py
Currently, if using Python 3.10, there is a warning saying that version is going to be deprecated and that is not properly tested.
=> fix: python version warning

doc/changelog.d/3574.miscellaneous.md, src/ansys/mapdl/core/launcher.py, tests/test_component.py, tests/test_launcher.py, tests/test_mapdl.py
=> feat: adding-mode-warning

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/examples.yml, doc/changelog.d/3572.documentation.md, doc/source/getting_started/install_pymapdl.rst, doc/source/user_guide/hpc/settings.rst, pyproject.toml
=> docs: updating compatible Python versions

doc/changelog.d/3576.miscellaneous.md, src/ansys/mapdl/core/__init__.py, src/ansys/mapdl/core/misc.py, tests/common.py, tests/test_launcher.py
Adding ``check_has_mapdl`` function. 
NA
=> feat: adding ``check_has_mapdl``

doc/changelog.d/3573.added.md, src/ansys/mapdl/core/__init__.py, src/ansys/mapdl/core/launcher.py, src/ansys/mapdl/core/licensing.py, src/ansys/mapdl/core/mapdl_core.py, src/ansys/mapdl/core/pool.py
=> refactor: replace `get_ansys_path` with `get_mapdl_path`

doc/changelog.d/3589.fixed.md, doc/source/conf.py, doc/source/getting_started/learning.rst, doc/source/getting_started/project.rst
=> fix: linkchecker and cheatsheet links

src/ansys/mapdl/core/mapdl_core.py, src/ansys/mapdl/core/mapdl_extended.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/conftest.py, tests/test_mapdl.py
This PR solves #3591 issue. This issue covers the instability/bug seen where MAPDL gets stuck while running some commands, very frequently, the `/SOLVE` command.
The reason for this is that some MAPDL printouts was making MAPDL to wait infinitely for the next line.
These specific prints in MAPDL terminal were coming from a debug messenger (``_MsgDbg1``), an object which prints more output (sometimes for debugging purposes) if it is activated.
It seems this debug messenger is activated by default, but deactivated if we issue `/VERIFY`.
Additionally, the debugger can be also activated if we activate the gRPC debug messenger (``mapdl._ctrl("set_verb", 5)``) since these kind of messengers are singleton objects (unique in the whole program).
MAPDL was getting stuck because for reading the …
=> fix: avoid verbose grpc interface when solving

doc/changelog.d/3617.fixed.md, src/ansys/mapdl/core/mapdl_grpc.py
This is very strange issue which I will have to check better.
Also we were killing the server twice on Windows, which made the second call frozen. 
Close #3616
=> fix: exit getting frozen if routine is not finished

.github/workflows/ci.yml, doc/changelog.d/3621.added.md, pyproject.toml
Set a timeout for each test
Related to #3577
=> tests: adding timeout to each test

doc/changelog.d/3247.fixed.md, doc/changelog.d/3640.fixed.md
Fix changelog format issue.
This was blocking a release
=> fix: changelog

.github/workflows/ci.yml, .github/workflows/linkchecker.yml, doc/changelog.d/3659.maintenance.md
=> ci: pin ubuntu OS to 22.04.

.ci/build_matrix.sh, .github/workflows/ci.yml, doc/changelog.d/3668.maintenance.md
=> ci: skipping students version if on remote

.github/workflows/ci.yml, doc/changelog.d/3669.maintenance.md
As the title.
The idea is to reduce the amount of jobs running in parallel.
NA
=> ci: reducing minimal and console to two versions, and after local and remote

doc/changelog.d/3662.fixed.md, src/ansys/mapdl/core/component.py, tests/test_component.py
=> fix: parsing components when too many

.ci/collect_mapdl_logs_locals.sh, .ci/collect_mapdl_logs_remote.sh, .ci/requirements_minimal.txt, .github/workflows/ci.yml, .gitignore, doc/changelog.d/3676.dependencies.md, pyproject.toml, tests/conftest.py
As the title. We need to keep a close eye into the time tests take.
NA
=> ci: adding-profiling-to-unit-tests

.ci/start_mapdl.sh, doc/changelog.d/3693.maintenance.md
This should help to improve MAPDL container estability.
Close #3378
=> ci: adding memory limitation to MAPDL command line

doc/changelog.d/3686.fixed.md, src/ansys/mapdl/core/errors.py, tests/common.py, tests/conftest.py, tests/test_grpc.py, tests/test_mapdl.py, tests/test_parameters.py, tests/test_xpl.py
Making sure we avoid executing more commands when exiting MAPDL.
Close #3685
=> fix: avoid MAPDL commands execution when gRPC connection fails.

.ci/start_mapdl.sh, doc/changelog.d/3693.maintenance.md, src/ansys/mapdl/core/mapdl_core.py, tests/test_mapdl.py
As the title. By using components instead of retrieving all entity ids, we speed up the process.
Previous implementation used `XSEL` functions to set the retrieved ids of the entities. While this was OK, it incurs in performance penalization because it has to write a file (sometimes quite big), transfer it and run it using `non_interactive`. Because of the amount of `XSEL,A,...` lines, this might posed a problem with the infamous gRPC instability (#3313).
I think the thorough testing should be sufficient to ensure we do not hit issues like https://github.com/ansys/pymapdl/issues/3372 or https://github.com/ansys/pymapdl/issues/2452
However can @mikerife have a look at the `test_save_selection_2` code and see if I am missing something?
Testing code is `test_save_selection_2`.
```
tmp_old.py …
```
=> feat: improving performance of save_selection

doc/changelog.d/3694.added.md, tests/test_mapdl.py
Adding tests to make sure the conversion `None` to `"None"` is correct.
Close #3660
=> test: adding tests asserting None are translated to "None".

doc/changelog.d/3703.added.md, src/ansys/mapdl/core/errors.py, src/ansys/mapdl/core/mapdl_grpc.py, src/ansys/mapdl/core/mesh_grpc.py, tests/common.py, tests/conftest.py, tests/test_grpc.py, tests/test_mapdl.py
=> test: improving testing performance

doc/changelog.d/3709.fixed.md, src/ansys/mapdl/core/mapdl_grpc.py, tests/common.py, tests/test_mapdl.py
To avoid raising issues when we are using the garbage collector and MAPDL is already dead.
NA
=> fix: using cached version for remove lock on exit

doc/changelog.d/3730.fixed.md, src/ansys/mapdl/core/launcher.py, tests/test_launcher.py
Not assuming RAM in GB
Close #3724
=> fix: ram units

doc/changelog.d/3737.documentation.md, doc/source/getting_started/develop_pymapdl.rst, doc/styles/config/vocabularies/ANSYS/accept.txt
=> docs: homogenizing commit/branches/pull request prefix

doc/changelog.d/3729.fixed.md, src/ansys/mapdl/core/_commands/solution/dynamic_options.py, src/ansys/mapdl/core/launcher.py, src/ansys/mapdl/core/mapdl_console.py, src/ansys/mapdl/core/mapdl_core.py, src/ansys/mapdl/core/mapdl_grpc.py, tests/conftest.py, tests/test_console.py, tests/test_mapdl.py
Kills MAPDL on object deletion if the instance was launched by that instance.
Close #3692
Close #3394 
Close #3514
=> fix: exiting on class deletion

doc/changelog.d/3745.fixed.md, src/ansys/mapdl/core/mapdl_extended.py, tests/test_mapdl.py, tests/test_parameters.py
**Please provide a brief description of the changes made in this pull request.**
mapdl behavior of *TREAD when column number is more than 2 is that it takes the first row as column header.
There are two possible scenarios :
1. Where the column header is defined in the text file. (#3305)
2. Where the column header is not defined. (we currently handle it internally in pymapdl copying the first row again).
fix attempted by introducing a keyword arg `col_header` to handle case with col_header.
when col_header=True do not go through the logic of copying the first row again. (which is why we see the issue in 3305).
update dim accordingly.
from #3305 updating the load_table cmd with the keyword arg `col_header`:True should fix the issue.
mapdl.load_table('acc_data', acceleration_data, …
=> fix: problem with the load_table method

doc/changelog.d/3747.fixed.md, tests/test_xpl.py
As the title. Avoiding issuing `/POST1` before solving.
Close #3714
=> fix: do all the cleaning commands before cleaning the database, so we avoid having to issue `/POST1`.

doc/changelog.d/3753.fixed.md, src/ansys/mapdl/core/misc.py, tests/test_plotting.py
**Please provide a brief description of the changes made in this pull request.**
Fix for #3349 
1. ksel, esel, nsel uses kabs (for field 7)
2. lsel, asel, vsel uses kswp (for field 7)
Wrappers on vsel and other related cmds - like `@allow_pickable_entities` use `_get_args_xsel` to get the args passed. This function currently accounts only for `kabs` , added logic for `kswp`. 
#3349 
- [] I have marked this PR as ``draft`` if it is not ready to be reviewed yet.
=> fix: Bug located in VSEL using KSWP field

doc/changelog.d/3759.fixed.md, src/ansys/mapdl/core/mapdl_grpc.py, tests/test_grpc.py
=> fix: avoid returning output when using input grpc method

doc/changelog.d/3758.fixed.md, doc/changelog.d/3769.fixed.md
As the title.
Fix release issue.
=> fix: removig star from command name in changelog

doc/changelog.d/3771.dependencies.md, pyproject.toml
Temporary avoid using the latest version of flit due to issues when releasing to PyPI with https://github.com/pypa/gh-action-pypi-publish. The problem comes from the new metadata format used to release and the fact the version of `pypa/gh-action-pypi-publish` we are using is not compatible with is. However, using a newer version is a problem, see ansys/actions#687 for more information on the blocking changes.
None
=> build: temporary avoid flit latest version

doc/changelog.d/3773.fixed.md, src/ansys/mapdl/core/component.py, src/ansys/mapdl/core/mesh_grpc.py, src/ansys/mapdl/core/pool.py, tests/test_pool.py
=> fix: missing pool name in test

doc/changelog.d/3771.dependencies.md, pyproject.toml, src/ansys/mapdl/core/common_grpc.py, src/ansys/mapdl/core/mesh_grpc.py, tests/test_mapdl.py, tests/test_mesh_grpc.py, tests/test_post.py
The idea is to make the code more resistant to crashes since we ensure we are switching back to previous state. It can also help to speed up some tests.
NA
=> feat: implement ignore cache reset context

doc/changelog.d/3784.fixed.md, src/ansys/mapdl/core/mesh/mesh.py, src/ansys/mapdl/core/post.py, tests/test_post.py
Fix crashes when having uncomplete selections.
Now, under the hood, for plotting nodes PyMAPDL will select the elements those nodes belong to so we can plot them and avoid crashes.
Close #3782
=> fix: improve element and node selection handling in post-processing

doc/changelog.d/3795.documentation.md, doc/source/changelog.rst, pyproject.toml
Adding references or tags to sections in `changelog` page.
Not applicable.
=> docs: adding reference to tags

.github/workflows/ci.yml, .github/workflows/docker_clean_untagged.yml, .github/workflows/label.yml, doc/changelog.d/3834.maintenance.md
As the title.
Close #3831
Close #3625
=> ci: update action versions to v9 in CI workflows

.github/workflows/ci.yml, doc/changelog.d/3837.maintenance.md
As the title.
Related to #3834
Related to #3831
=> feat: update CI workflow to release to PyPI using trusted publisher

doc/changelog.d/3854.fixed.md, src/ansys/mapdl/core/cli/convert.py
Adding missing types to convert CLI
Close #3841
=> fix: specify type for click options in convert.py

.github/workflows/doc-build.yml, .github/workflows/linkchecker.yml, doc/changelog.d/3850.fixed.md, doc/source/conf.py
=> fix: linkchecker

doc/changelog.d/3855.fixed.md, src/ansys/mapdl/core/launcher.py, src/ansys/mapdl/core/misc.py
Better annotations on `launch_mapdl`. Also reordering arguments to be alphabetically ordered. 
Improving docstring.
Close #3813
=> fix: annotate launch_mapdl and better docstring

doc/changelog.d/3915.fixed.md, src/ansys/mapdl/core/mapdl_inprocess.py
Fixes #3916
`mapdl_inprocess` should use `None` for graphics backend. This will have to be revisited with some automated tests when 2025R2 is released.
=> fix: Change the mapdl_inprocess graphics backend

.github/workflows/doc-build.yml, doc/changelog.d/4118.fixed.md, doc/changelog.d/4132.fixed.md, doc/changelog.d/4132.miscellaneous.md
This reverts commit 502a5e22aa885549657e1e602f594065b81b8db7.
Also update the MAPDL container to use ``v25.2-ubuntu-amd``.
The examples upload files to the DPF docker container, that fails if using ubuntu.
Discovered in #4131 
Related to https://github.com/ansys/pydpf-core/issues/2254
=> fix: doc build workflow by using two containers: MAPDL and DPF

.github/workflows/doc-build.yml, .github/workflows/test-local.yml, .github/workflows/test-remote.yml, doc/changelog.d/4239.maintenance.md
Comment out the log upload steps in the workflow files to prevent unnecessary uploads during the CI process.
=> ci: comment out log upload steps in workflow files
